/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _cairo_path_data_t_point {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _cairo_path_data_t_point(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_cairo_path_data_t_point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cairoJNI.delete__cairo_path_data_t_point(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    cairoJNI._cairo_path_data_t_point_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return cairoJNI._cairo_path_data_t_point_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    cairoJNI._cairo_path_data_t_point_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return cairoJNI._cairo_path_data_t_point_y_get(swigCPtr, this);
  }

  public _cairo_path_data_t_point() {
    this(cairoJNI.new__cairo_path_data_t_point(), true);
  }

}
