/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GDate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GDate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setJulian_days(long value) {
    pangoJNI._GDate_julian_days_set(swigCPtr, this, value);
  }

  public long getJulian_days() {
    return pangoJNI._GDate_julian_days_get(swigCPtr, this);
  }

  public void setJulian(long value) {
    pangoJNI._GDate_julian_set(swigCPtr, this, value);
  }

  public long getJulian() {
    return pangoJNI._GDate_julian_get(swigCPtr, this);
  }

  public void setDmy(long value) {
    pangoJNI._GDate_dmy_set(swigCPtr, this, value);
  }

  public long getDmy() {
    return pangoJNI._GDate_dmy_get(swigCPtr, this);
  }

  public void setDay(long value) {
    pangoJNI._GDate_day_set(swigCPtr, this, value);
  }

  public long getDay() {
    return pangoJNI._GDate_day_get(swigCPtr, this);
  }

  public void setMonth(long value) {
    pangoJNI._GDate_month_set(swigCPtr, this, value);
  }

  public long getMonth() {
    return pangoJNI._GDate_month_get(swigCPtr, this);
  }

  public void setYear(long value) {
    pangoJNI._GDate_year_set(swigCPtr, this, value);
  }

  public long getYear() {
    return pangoJNI._GDate_year_get(swigCPtr, this);
  }

  public _GDate() {
    this(pangoJNI.new__GDate(), true);
  }

}
