/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GDoubleIEEE754_mpn {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDoubleIEEE754_mpn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDoubleIEEE754_mpn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GDoubleIEEE754_mpn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMantissa_low(long value) {
    pangoJNI._GDoubleIEEE754_mpn_mantissa_low_set(swigCPtr, this, value);
  }

  public long getMantissa_low() {
    return pangoJNI._GDoubleIEEE754_mpn_mantissa_low_get(swigCPtr, this);
  }

  public void setMantissa_high(long value) {
    pangoJNI._GDoubleIEEE754_mpn_mantissa_high_set(swigCPtr, this, value);
  }

  public long getMantissa_high() {
    return pangoJNI._GDoubleIEEE754_mpn_mantissa_high_get(swigCPtr, this);
  }

  public void setBiased_exponent(long value) {
    pangoJNI._GDoubleIEEE754_mpn_biased_exponent_set(swigCPtr, this, value);
  }

  public long getBiased_exponent() {
    return pangoJNI._GDoubleIEEE754_mpn_biased_exponent_get(swigCPtr, this);
  }

  public void setSign(long value) {
    pangoJNI._GDoubleIEEE754_mpn_sign_set(swigCPtr, this, value);
  }

  public long getSign() {
    return pangoJNI._GDoubleIEEE754_mpn_sign_get(swigCPtr, this);
  }

  public _GDoubleIEEE754_mpn() {
    this(pangoJNI.new__GDoubleIEEE754_mpn(), true);
  }

}
