/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GError {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GError(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GError obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GError(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDomain(long value) {
    pangoJNI._GError_domain_set(swigCPtr, this, value);
  }

  public long getDomain() {
    return pangoJNI._GError_domain_get(swigCPtr, this);
  }

  public void setCode(int value) {
    pangoJNI._GError_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return pangoJNI._GError_code_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    pangoJNI._GError_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return pangoJNI._GError_message_get(swigCPtr, this);
  }

  public _GError() {
    this(pangoJNI.new__GError(), true);
  }

}
