/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GHookList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GHookList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GHookList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GHookList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSeq_id(long value) {
    pangoJNI._GHookList_seq_id_set(swigCPtr, this, value);
  }

  public long getSeq_id() {
    return pangoJNI._GHookList_seq_id_get(swigCPtr, this);
  }

  public void setHook_size(long value) {
    pangoJNI._GHookList_hook_size_set(swigCPtr, this, value);
  }

  public long getHook_size() {
    return pangoJNI._GHookList_hook_size_get(swigCPtr, this);
  }

  public void setIs_setup(long value) {
    pangoJNI._GHookList_is_setup_set(swigCPtr, this, value);
  }

  public long getIs_setup() {
    return pangoJNI._GHookList_is_setup_get(swigCPtr, this);
  }

  public void setHooks(_GHook value) {
    pangoJNI._GHookList_hooks_set(swigCPtr, this, _GHook.getCPtr(value), value);
  }

  public _GHook getHooks() {
    long cPtr = pangoJNI._GHookList_hooks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GHook(cPtr, false);
  }

  public void setDummy3(SWIGTYPE_p_void value) {
    pangoJNI._GHookList_dummy3_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getDummy3() {
    long cPtr = pangoJNI._GHookList_dummy3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFinalize_hook(SWIGTYPE_p_f_p_struct__GHookList_p_struct__GHook__void value) {
    pangoJNI._GHookList_finalize_hook_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GHookList_p_struct__GHook__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GHookList_p_struct__GHook__void getFinalize_hook() {
    long cPtr = pangoJNI._GHookList_finalize_hook_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GHookList_p_struct__GHook__void(cPtr, false);
  }

  public void setDummy(SWIGTYPE_p_p_void value) {
    pangoJNI._GHookList_dummy_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getDummy() {
    long cPtr = pangoJNI._GHookList_dummy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _GHookList() {
    this(pangoJNI.new__GHookList(), true);
  }

}
