/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GIOChannel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GIOChannel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GIOChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GIOChannel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRef_count(int value) {
    pangoJNI._GIOChannel_ref_count_set(swigCPtr, this, value);
  }

  public int getRef_count() {
    return pangoJNI._GIOChannel_ref_count_get(swigCPtr, this);
  }

  public void setFuncs(_GIOFuncs value) {
    pangoJNI._GIOChannel_funcs_set(swigCPtr, this, _GIOFuncs.getCPtr(value), value);
  }

  public _GIOFuncs getFuncs() {
    long cPtr = pangoJNI._GIOChannel_funcs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GIOFuncs(cPtr, false);
  }

  public void setEncoding(String value) {
    pangoJNI._GIOChannel_encoding_set(swigCPtr, this, value);
  }

  public String getEncoding() {
    return pangoJNI._GIOChannel_encoding_get(swigCPtr, this);
  }

  public void setRead_cd(SWIGTYPE_p__GIConv value) {
    pangoJNI._GIOChannel_read_cd_set(swigCPtr, this, SWIGTYPE_p__GIConv.getCPtr(value));
  }

  public SWIGTYPE_p__GIConv getRead_cd() {
    long cPtr = pangoJNI._GIOChannel_read_cd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GIConv(cPtr, false);
  }

  public void setWrite_cd(SWIGTYPE_p__GIConv value) {
    pangoJNI._GIOChannel_write_cd_set(swigCPtr, this, SWIGTYPE_p__GIConv.getCPtr(value));
  }

  public SWIGTYPE_p__GIConv getWrite_cd() {
    long cPtr = pangoJNI._GIOChannel_write_cd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GIConv(cPtr, false);
  }

  public void setLine_term(String value) {
    pangoJNI._GIOChannel_line_term_set(swigCPtr, this, value);
  }

  public String getLine_term() {
    return pangoJNI._GIOChannel_line_term_get(swigCPtr, this);
  }

  public void setLine_term_len(long value) {
    pangoJNI._GIOChannel_line_term_len_set(swigCPtr, this, value);
  }

  public long getLine_term_len() {
    return pangoJNI._GIOChannel_line_term_len_get(swigCPtr, this);
  }

  public void setBuf_size(java.math.BigInteger value) {
    pangoJNI._GIOChannel_buf_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBuf_size() {
    return pangoJNI._GIOChannel_buf_size_get(swigCPtr, this);
  }

  public void setRead_buf(_GString value) {
    pangoJNI._GIOChannel_read_buf_set(swigCPtr, this, _GString.getCPtr(value), value);
  }

  public _GString getRead_buf() {
    long cPtr = pangoJNI._GIOChannel_read_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GString(cPtr, false);
  }

  public void setEncoded_read_buf(_GString value) {
    pangoJNI._GIOChannel_encoded_read_buf_set(swigCPtr, this, _GString.getCPtr(value), value);
  }

  public _GString getEncoded_read_buf() {
    long cPtr = pangoJNI._GIOChannel_encoded_read_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GString(cPtr, false);
  }

  public void setWrite_buf(_GString value) {
    pangoJNI._GIOChannel_write_buf_set(swigCPtr, this, _GString.getCPtr(value), value);
  }

  public _GString getWrite_buf() {
    long cPtr = pangoJNI._GIOChannel_write_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GString(cPtr, false);
  }

  public void setPartial_write_buf(String value) {
    pangoJNI._GIOChannel_partial_write_buf_set(swigCPtr, this, value);
  }

  public String getPartial_write_buf() {
    return pangoJNI._GIOChannel_partial_write_buf_get(swigCPtr, this);
  }

  public void setUse_buffer(long value) {
    pangoJNI._GIOChannel_use_buffer_set(swigCPtr, this, value);
  }

  public long getUse_buffer() {
    return pangoJNI._GIOChannel_use_buffer_get(swigCPtr, this);
  }

  public void setDo_encode(long value) {
    pangoJNI._GIOChannel_do_encode_set(swigCPtr, this, value);
  }

  public long getDo_encode() {
    return pangoJNI._GIOChannel_do_encode_get(swigCPtr, this);
  }

  public void setClose_on_unref(long value) {
    pangoJNI._GIOChannel_close_on_unref_set(swigCPtr, this, value);
  }

  public long getClose_on_unref() {
    return pangoJNI._GIOChannel_close_on_unref_get(swigCPtr, this);
  }

  public void setIs_readable(long value) {
    pangoJNI._GIOChannel_is_readable_set(swigCPtr, this, value);
  }

  public long getIs_readable() {
    return pangoJNI._GIOChannel_is_readable_get(swigCPtr, this);
  }

  public void setIs_writeable(long value) {
    pangoJNI._GIOChannel_is_writeable_set(swigCPtr, this, value);
  }

  public long getIs_writeable() {
    return pangoJNI._GIOChannel_is_writeable_get(swigCPtr, this);
  }

  public void setIs_seekable(long value) {
    pangoJNI._GIOChannel_is_seekable_set(swigCPtr, this, value);
  }

  public long getIs_seekable() {
    return pangoJNI._GIOChannel_is_seekable_get(swigCPtr, this);
  }

  public void setReserved1(SWIGTYPE_p_void value) {
    pangoJNI._GIOChannel_reserved1_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved1() {
    long cPtr = pangoJNI._GIOChannel_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_void value) {
    pangoJNI._GIOChannel_reserved2_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getReserved2() {
    long cPtr = pangoJNI._GIOChannel_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public _GIOChannel() {
    this(pangoJNI.new__GIOChannel(), true);
  }

}
