/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    pangoJNI._GList_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = pangoJNI._GList_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setNext(_GList value) {
    pangoJNI._GList_next_set(swigCPtr, this, _GList.getCPtr(value), value);
  }

  public _GList getNext() {
    long cPtr = pangoJNI._GList_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GList(cPtr, false);
  }

  public void setPrev(_GList value) {
    pangoJNI._GList_prev_set(swigCPtr, this, _GList.getCPtr(value), value);
  }

  public _GList getPrev() {
    long cPtr = pangoJNI._GList_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GList(cPtr, false);
  }

  public _GList() {
    this(pangoJNI.new__GList(), true);
  }

}
