/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GMarkupParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GMarkupParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GMarkupParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GMarkupParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart_element(SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_p_q_const__char_p_p_q_const__char_p_void_p_p_struct__GError__void value) {
    pangoJNI._GMarkupParser_start_element_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_p_q_const__char_p_p_q_const__char_p_void_p_p_struct__GError__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_p_q_const__char_p_p_q_const__char_p_void_p_p_struct__GError__void getStart_element() {
    long cPtr = pangoJNI._GMarkupParser_start_element_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_p_q_const__char_p_p_q_const__char_p_void_p_p_struct__GError__void(cPtr, false);
  }

  public void setEnd_element(SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_void_p_p_struct__GError__void value) {
    pangoJNI._GMarkupParser_end_element_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_void_p_p_struct__GError__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_void_p_p_struct__GError__void getEnd_element() {
    long cPtr = pangoJNI._GMarkupParser_end_element_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_p_void_p_p_struct__GError__void(cPtr, false);
  }

  public void setText(SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void value) {
    pangoJNI._GMarkupParser_text_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void getText() {
    long cPtr = pangoJNI._GMarkupParser_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void(cPtr, false);
  }

  public void setPassthrough(SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void value) {
    pangoJNI._GMarkupParser_passthrough_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void getPassthrough() {
    long cPtr = pangoJNI._GMarkupParser_passthrough_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_q_const__char_unsigned_long_long_p_void_p_p_struct__GError__void(cPtr, false);
  }

  public void setError(SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_struct__GError_p_void__void value) {
    pangoJNI._GMarkupParser_error_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_struct__GError_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_struct__GError_p_void__void getError() {
    long cPtr = pangoJNI._GMarkupParser_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GMarkupParseContext_p_struct__GError_p_void__void(cPtr, false);
  }

  public _GMarkupParser() {
    this(pangoJNI.new__GMarkupParser(), true);
  }

}
