/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GMemVTable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GMemVTable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GMemVTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GMemVTable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMalloc(SWIGTYPE_p_f_unsigned_long_long__p_void value) {
    pangoJNI._GMemVTable_malloc_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_long_long__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_long_long__p_void getMalloc() {
    long cPtr = pangoJNI._GMemVTable_malloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_long_long__p_void(cPtr, false);
  }

  public void setRealloc(SWIGTYPE_p_f_p_void_unsigned_long_long__p_void value) {
    pangoJNI._GMemVTable_realloc_set(swigCPtr, this, SWIGTYPE_p_f_p_void_unsigned_long_long__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_unsigned_long_long__p_void getRealloc() {
    long cPtr = pangoJNI._GMemVTable_realloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_unsigned_long_long__p_void(cPtr, false);
  }

  public void setFree(SWIGTYPE_p_f_p_void__void value) {
    pangoJNI._GMemVTable_free_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getFree() {
    long cPtr = pangoJNI._GMemVTable_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setCalloc(SWIGTYPE_p_f_unsigned_long_long_unsigned_long_long__p_void value) {
    pangoJNI._GMemVTable_calloc_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_long_long_unsigned_long_long__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_long_long_unsigned_long_long__p_void getCalloc() {
    long cPtr = pangoJNI._GMemVTable_calloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_long_long_unsigned_long_long__p_void(cPtr, false);
  }

  public void setTry_malloc(SWIGTYPE_p_f_unsigned_long_long__p_void value) {
    pangoJNI._GMemVTable_try_malloc_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_long_long__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_long_long__p_void getTry_malloc() {
    long cPtr = pangoJNI._GMemVTable_try_malloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_long_long__p_void(cPtr, false);
  }

  public void setTry_realloc(SWIGTYPE_p_f_p_void_unsigned_long_long__p_void value) {
    pangoJNI._GMemVTable_try_realloc_set(swigCPtr, this, SWIGTYPE_p_f_p_void_unsigned_long_long__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_unsigned_long_long__p_void getTry_realloc() {
    long cPtr = pangoJNI._GMemVTable_try_realloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_unsigned_long_long__p_void(cPtr, false);
  }

  public _GMemVTable() {
    this(pangoJNI.new__GMemVTable(), true);
  }

}
