/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_type_instance(_GTypeInstance value) {
    pangoJNI._GObject_g_type_instance_set(swigCPtr, this, _GTypeInstance.getCPtr(value), value);
  }

  public _GTypeInstance getG_type_instance() {
    long cPtr = pangoJNI._GObject_g_type_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeInstance(cPtr, false);
  }

  public void setRef_count(long value) {
    pangoJNI._GObject_ref_count_set(swigCPtr, this, value);
  }

  public long getRef_count() {
    return pangoJNI._GObject_ref_count_get(swigCPtr, this);
  }

  public void setQdata(SWIGTYPE_p__GData value) {
    pangoJNI._GObject_qdata_set(swigCPtr, this, SWIGTYPE_p__GData.getCPtr(value));
  }

  public SWIGTYPE_p__GData getQdata() {
    long cPtr = pangoJNI._GObject_qdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GData(cPtr, false);
  }

  public _GObject() {
    this(pangoJNI.new__GObject(), true);
  }

}
