/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GOptionEntry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GOptionEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GOptionEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GOptionEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLong_name(String value) {
    pangoJNI._GOptionEntry_long_name_set(swigCPtr, this, value);
  }

  public String getLong_name() {
    return pangoJNI._GOptionEntry_long_name_get(swigCPtr, this);
  }

  public void setShort_name(char value) {
    pangoJNI._GOptionEntry_short_name_set(swigCPtr, this, value);
  }

  public char getShort_name() {
    return pangoJNI._GOptionEntry_short_name_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    pangoJNI._GOptionEntry_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return pangoJNI._GOptionEntry_flags_get(swigCPtr, this);
  }

  public void setArg(GOptionArg value) {
    pangoJNI._GOptionEntry_arg_set(swigCPtr, this, value.swigValue());
  }

  public GOptionArg getArg() {
    return GOptionArg.swigToEnum(pangoJNI._GOptionEntry_arg_get(swigCPtr, this));
  }

  public void setArg_data(SWIGTYPE_p_void value) {
    pangoJNI._GOptionEntry_arg_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getArg_data() {
    long cPtr = pangoJNI._GOptionEntry_arg_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDescription(String value) {
    pangoJNI._GOptionEntry_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return pangoJNI._GOptionEntry_description_get(swigCPtr, this);
  }

  public void setArg_description(String value) {
    pangoJNI._GOptionEntry_arg_description_set(swigCPtr, this, value);
  }

  public String getArg_description() {
    return pangoJNI._GOptionEntry_arg_description_get(swigCPtr, this);
  }

  public _GOptionEntry() {
    this(pangoJNI.new__GOptionEntry(), true);
  }

}
