/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GParamSpecGType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecGType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecGType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GParamSpecGType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GParamSpec value) {
    pangoJNI._GParamSpecGType_parent_instance_set(swigCPtr, this, _GParamSpec.getCPtr(value), value);
  }

  public _GParamSpec getParent_instance() {
    long cPtr = pangoJNI._GParamSpecGType_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GParamSpec(cPtr, false);
  }

  public void setIs_a_type(java.math.BigInteger value) {
    pangoJNI._GParamSpecGType_is_a_type_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getIs_a_type() {
    return pangoJNI._GParamSpecGType_is_a_type_get(swigCPtr, this);
  }

  public _GParamSpecGType() {
    this(pangoJNI.new__GParamSpecGType(), true);
  }

}
