/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GParamSpecString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GParamSpecString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GParamSpec value) {
    pangoJNI._GParamSpecString_parent_instance_set(swigCPtr, this, _GParamSpec.getCPtr(value), value);
  }

  public _GParamSpec getParent_instance() {
    long cPtr = pangoJNI._GParamSpecString_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GParamSpec(cPtr, false);
  }

  public void setDefault_value(String value) {
    pangoJNI._GParamSpecString_default_value_set(swigCPtr, this, value);
  }

  public String getDefault_value() {
    return pangoJNI._GParamSpecString_default_value_get(swigCPtr, this);
  }

  public void setCset_first(String value) {
    pangoJNI._GParamSpecString_cset_first_set(swigCPtr, this, value);
  }

  public String getCset_first() {
    return pangoJNI._GParamSpecString_cset_first_get(swigCPtr, this);
  }

  public void setCset_nth(String value) {
    pangoJNI._GParamSpecString_cset_nth_set(swigCPtr, this, value);
  }

  public String getCset_nth() {
    return pangoJNI._GParamSpecString_cset_nth_get(swigCPtr, this);
  }

  public void setSubstitutor(char value) {
    pangoJNI._GParamSpecString_substitutor_set(swigCPtr, this, value);
  }

  public char getSubstitutor() {
    return pangoJNI._GParamSpecString_substitutor_get(swigCPtr, this);
  }

  public void setNull_fold_if_empty(long value) {
    pangoJNI._GParamSpecString_null_fold_if_empty_set(swigCPtr, this, value);
  }

  public long getNull_fold_if_empty() {
    return pangoJNI._GParamSpecString_null_fold_if_empty_get(swigCPtr, this);
  }

  public void setEnsure_non_null(long value) {
    pangoJNI._GParamSpecString_ensure_non_null_set(swigCPtr, this, value);
  }

  public long getEnsure_non_null() {
    return pangoJNI._GParamSpecString_ensure_non_null_get(swigCPtr, this);
  }

  public _GParamSpecString() {
    this(pangoJNI.new__GParamSpecString(), true);
  }

}
