/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GParamSpecDouble {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GParamSpecDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GParamSpec value) {
    pangoJNI._GParamSpecDouble_parent_instance_set(swigCPtr, this, _GParamSpec.getCPtr(value), value);
  }

  public _GParamSpec getParent_instance() {
    long cPtr = pangoJNI._GParamSpecDouble_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GParamSpec(cPtr, false);
  }

  public void setMinimum(double value) {
    pangoJNI._GParamSpecDouble_minimum_set(swigCPtr, this, value);
  }

  public double getMinimum() {
    return pangoJNI._GParamSpecDouble_minimum_get(swigCPtr, this);
  }

  public void setMaximum(double value) {
    pangoJNI._GParamSpecDouble_maximum_set(swigCPtr, this, value);
  }

  public double getMaximum() {
    return pangoJNI._GParamSpecDouble_maximum_get(swigCPtr, this);
  }

  public void setDefault_value(double value) {
    pangoJNI._GParamSpecDouble_default_value_set(swigCPtr, this, value);
  }

  public double getDefault_value() {
    return pangoJNI._GParamSpecDouble_default_value_get(swigCPtr, this);
  }

  public void setEpsilon(double value) {
    pangoJNI._GParamSpecDouble_epsilon_set(swigCPtr, this, value);
  }

  public double getEpsilon() {
    return pangoJNI._GParamSpecDouble_epsilon_get(swigCPtr, this);
  }

  public _GParamSpecDouble() {
    this(pangoJNI.new__GParamSpecDouble(), true);
  }

}
