/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GParamSpecULong {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecULong(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecULong obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GParamSpecULong(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GParamSpec value) {
    pangoJNI._GParamSpecULong_parent_instance_set(swigCPtr, this, _GParamSpec.getCPtr(value), value);
  }

  public _GParamSpec getParent_instance() {
    long cPtr = pangoJNI._GParamSpecULong_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GParamSpec(cPtr, false);
  }

  public void setMinimum(long value) {
    pangoJNI._GParamSpecULong_minimum_set(swigCPtr, this, value);
  }

  public long getMinimum() {
    return pangoJNI._GParamSpecULong_minimum_get(swigCPtr, this);
  }

  public void setMaximum(long value) {
    pangoJNI._GParamSpecULong_maximum_set(swigCPtr, this, value);
  }

  public long getMaximum() {
    return pangoJNI._GParamSpecULong_maximum_get(swigCPtr, this);
  }

  public void setDefault_value(long value) {
    pangoJNI._GParamSpecULong_default_value_set(swigCPtr, this, value);
  }

  public long getDefault_value() {
    return pangoJNI._GParamSpecULong_default_value_get(swigCPtr, this);
  }

  public _GParamSpecULong() {
    this(pangoJNI.new__GParamSpecULong(), true);
  }

}
