/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GPollFD {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GPollFD(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GPollFD obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GPollFD(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFd(long value) {
    pangoJNI._GPollFD_fd_set(swigCPtr, this, value);
  }

  public long getFd() {
    return pangoJNI._GPollFD_fd_get(swigCPtr, this);
  }

  public void setEvents(int value) {
    pangoJNI._GPollFD_events_set(swigCPtr, this, value);
  }

  public int getEvents() {
    return pangoJNI._GPollFD_events_get(swigCPtr, this);
  }

  public void setRevents(int value) {
    pangoJNI._GPollFD_revents_set(swigCPtr, this, value);
  }

  public int getRevents() {
    return pangoJNI._GPollFD_revents_get(swigCPtr, this);
  }

  public _GPollFD() {
    this(pangoJNI.new__GPollFD(), true);
  }

}
