/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GScanner {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GScanner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GScanner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GScanner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser_data(SWIGTYPE_p_void value) {
    pangoJNI._GScanner_user_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUser_data() {
    long cPtr = pangoJNI._GScanner_user_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setMax_parse_errors(long value) {
    pangoJNI._GScanner_max_parse_errors_set(swigCPtr, this, value);
  }

  public long getMax_parse_errors() {
    return pangoJNI._GScanner_max_parse_errors_get(swigCPtr, this);
  }

  public void setParse_errors(long value) {
    pangoJNI._GScanner_parse_errors_set(swigCPtr, this, value);
  }

  public long getParse_errors() {
    return pangoJNI._GScanner_parse_errors_get(swigCPtr, this);
  }

  public void setInput_name(String value) {
    pangoJNI._GScanner_input_name_set(swigCPtr, this, value);
  }

  public String getInput_name() {
    return pangoJNI._GScanner_input_name_get(swigCPtr, this);
  }

  public void setQdata(SWIGTYPE_p__GData value) {
    pangoJNI._GScanner_qdata_set(swigCPtr, this, SWIGTYPE_p__GData.getCPtr(value));
  }

  public SWIGTYPE_p__GData getQdata() {
    long cPtr = pangoJNI._GScanner_qdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GData(cPtr, false);
  }

  public void setConfig(_GScannerConfig value) {
    pangoJNI._GScanner_config_set(swigCPtr, this, _GScannerConfig.getCPtr(value), value);
  }

  public _GScannerConfig getConfig() {
    long cPtr = pangoJNI._GScanner_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GScannerConfig(cPtr, false);
  }

  public void setToken(GTokenType value) {
    pangoJNI._GScanner_token_set(swigCPtr, this, value.swigValue());
  }

  public GTokenType getToken() {
    return GTokenType.swigToEnum(pangoJNI._GScanner_token_get(swigCPtr, this));
  }

  public void setValue(_GTokenValue value) {
    pangoJNI._GScanner_value_set(swigCPtr, this, _GTokenValue.getCPtr(value), value);
  }

  public _GTokenValue getValue() {
    long cPtr = pangoJNI._GScanner_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTokenValue(cPtr, false);
  }

  public void setLine(long value) {
    pangoJNI._GScanner_line_set(swigCPtr, this, value);
  }

  public long getLine() {
    return pangoJNI._GScanner_line_get(swigCPtr, this);
  }

  public void setPosition(long value) {
    pangoJNI._GScanner_position_set(swigCPtr, this, value);
  }

  public long getPosition() {
    return pangoJNI._GScanner_position_get(swigCPtr, this);
  }

  public void setNext_token(GTokenType value) {
    pangoJNI._GScanner_next_token_set(swigCPtr, this, value.swigValue());
  }

  public GTokenType getNext_token() {
    return GTokenType.swigToEnum(pangoJNI._GScanner_next_token_get(swigCPtr, this));
  }

  public void setNext_value(_GTokenValue value) {
    pangoJNI._GScanner_next_value_set(swigCPtr, this, _GTokenValue.getCPtr(value), value);
  }

  public _GTokenValue getNext_value() {
    long cPtr = pangoJNI._GScanner_next_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTokenValue(cPtr, false);
  }

  public void setNext_line(long value) {
    pangoJNI._GScanner_next_line_set(swigCPtr, this, value);
  }

  public long getNext_line() {
    return pangoJNI._GScanner_next_line_get(swigCPtr, this);
  }

  public void setNext_position(long value) {
    pangoJNI._GScanner_next_position_set(swigCPtr, this, value);
  }

  public long getNext_position() {
    return pangoJNI._GScanner_next_position_get(swigCPtr, this);
  }

  public void setSymbol_table(SWIGTYPE_p__GHashTable value) {
    pangoJNI._GScanner_symbol_table_set(swigCPtr, this, SWIGTYPE_p__GHashTable.getCPtr(value));
  }

  public SWIGTYPE_p__GHashTable getSymbol_table() {
    long cPtr = pangoJNI._GScanner_symbol_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GHashTable(cPtr, false);
  }

  public void setInput_fd(int value) {
    pangoJNI._GScanner_input_fd_set(swigCPtr, this, value);
  }

  public int getInput_fd() {
    return pangoJNI._GScanner_input_fd_get(swigCPtr, this);
  }

  public void setText(String value) {
    pangoJNI._GScanner_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return pangoJNI._GScanner_text_get(swigCPtr, this);
  }

  public void setText_end(String value) {
    pangoJNI._GScanner_text_end_set(swigCPtr, this, value);
  }

  public String getText_end() {
    return pangoJNI._GScanner_text_end_get(swigCPtr, this);
  }

  public void setBuffer(String value) {
    pangoJNI._GScanner_buffer_set(swigCPtr, this, value);
  }

  public String getBuffer() {
    return pangoJNI._GScanner_buffer_get(swigCPtr, this);
  }

  public void setScope_id(long value) {
    pangoJNI._GScanner_scope_id_set(swigCPtr, this, value);
  }

  public long getScope_id() {
    return pangoJNI._GScanner_scope_id_get(swigCPtr, this);
  }

  public void setMsg_handler(SWIGTYPE_p_f_p_struct__GScanner_p_char_int__void value) {
    pangoJNI._GScanner_msg_handler_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GScanner_p_char_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GScanner_p_char_int__void getMsg_handler() {
    long cPtr = pangoJNI._GScanner_msg_handler_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GScanner_p_char_int__void(cPtr, false);
  }

  public _GScanner() {
    this(pangoJNI.new__GScanner(), true);
  }

}
