/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GSignalQuery {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GSignalQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GSignalQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GSignalQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSignal_id(long value) {
    pangoJNI._GSignalQuery_signal_id_set(swigCPtr, this, value);
  }

  public long getSignal_id() {
    return pangoJNI._GSignalQuery_signal_id_get(swigCPtr, this);
  }

  public void setSignal_name(String value) {
    pangoJNI._GSignalQuery_signal_name_set(swigCPtr, this, value);
  }

  public String getSignal_name() {
    return pangoJNI._GSignalQuery_signal_name_get(swigCPtr, this);
  }

  public void setItype(java.math.BigInteger value) {
    pangoJNI._GSignalQuery_itype_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getItype() {
    return pangoJNI._GSignalQuery_itype_get(swigCPtr, this);
  }

  public void setSignal_flags(GSignalFlags value) {
    pangoJNI._GSignalQuery_signal_flags_set(swigCPtr, this, value.swigValue());
  }

  public GSignalFlags getSignal_flags() {
    return GSignalFlags.swigToEnum(pangoJNI._GSignalQuery_signal_flags_get(swigCPtr, this));
  }

  public void setReturn_type(java.math.BigInteger value) {
    pangoJNI._GSignalQuery_return_type_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getReturn_type() {
    return pangoJNI._GSignalQuery_return_type_get(swigCPtr, this);
  }

  public void setN_params(long value) {
    pangoJNI._GSignalQuery_n_params_set(swigCPtr, this, value);
  }

  public long getN_params() {
    return pangoJNI._GSignalQuery_n_params_get(swigCPtr, this);
  }

  public void setParam_types(SWIGTYPE_p_unsigned_long_long value) {
    pangoJNI._GSignalQuery_param_types_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getParam_types() {
    long cPtr = pangoJNI._GSignalQuery_param_types_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public _GSignalQuery() {
    this(pangoJNI.new__GSignalQuery(), true);
  }

}
