/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GSList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GSList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GSList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GSList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    pangoJNI._GSList_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = pangoJNI._GSList_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setNext(_GSList value) {
    pangoJNI._GSList_next_set(swigCPtr, this, _GSList.getCPtr(value), value);
  }

  public _GSList getNext() {
    long cPtr = pangoJNI._GSList_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSList(cPtr, false);
  }

  public _GSList() {
    this(pangoJNI.new__GSList(), true);
  }

}
