/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GSourceCallbackFuncs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GSourceCallbackFuncs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GSourceCallbackFuncs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GSourceCallbackFuncs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRef(SWIGTYPE_p_f_p_void__void value) {
    pangoJNI._GSourceCallbackFuncs_ref_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getRef() {
    long cPtr = pangoJNI._GSourceCallbackFuncs_ref_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setUnref(SWIGTYPE_p_f_p_void__void value) {
    pangoJNI._GSourceCallbackFuncs_unref_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getUnref() {
    long cPtr = pangoJNI._GSourceCallbackFuncs_unref_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setGet(SWIGTYPE_p_f_p_void_p_struct__GSource_p_p_f_p_void__int_p_p_void__void value) {
    pangoJNI._GSourceCallbackFuncs_get_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_struct__GSource_p_p_f_p_void__int_p_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_struct__GSource_p_p_f_p_void__int_p_p_void__void getGet() {
    long cPtr = pangoJNI._GSourceCallbackFuncs_get_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_struct__GSource_p_p_f_p_void__int_p_p_void__void(cPtr, false);
  }

  public _GSourceCallbackFuncs() {
    this(pangoJNI.new__GSourceCallbackFuncs(), true);
  }

}
