/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GStaticRecMutex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GStaticRecMutex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GStaticRecMutex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GStaticRecMutex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutex(GStaticMutex value) {
    pangoJNI._GStaticRecMutex_mutex_set(swigCPtr, this, GStaticMutex.getCPtr(value), value);
  }

  public GStaticMutex getMutex() {
    long cPtr = pangoJNI._GStaticRecMutex_mutex_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GStaticMutex(cPtr, false);
  }

  public void setDepth(long value) {
    pangoJNI._GStaticRecMutex_depth_set(swigCPtr, this, value);
  }

  public long getDepth() {
    return pangoJNI._GStaticRecMutex_depth_get(swigCPtr, this);
  }

  public _GStaticRecMutex_unused getUnused() {
    long cPtr = pangoJNI._GStaticRecMutex_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GStaticRecMutex_unused(cPtr, false);
  }

  public _GStaticRecMutex() {
    this(pangoJNI.new__GStaticRecMutex(), true);
  }

}
