/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GThread {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GThread(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GThread obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GThread(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFunc(SWIGTYPE_p_f_p_void__p_void value) {
    pangoJNI._GThread_func_set(swigCPtr, this, SWIGTYPE_p_f_p_void__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__p_void getFunc() {
    long cPtr = pangoJNI._GThread_func_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__p_void(cPtr, false);
  }

  public void setData(SWIGTYPE_p_void value) {
    pangoJNI._GThread_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = pangoJNI._GThread_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setJoinable(int value) {
    pangoJNI._GThread_joinable_set(swigCPtr, this, value);
  }

  public int getJoinable() {
    return pangoJNI._GThread_joinable_get(swigCPtr, this);
  }

  public void setPriority(GThreadPriority value) {
    pangoJNI._GThread_priority_set(swigCPtr, this, value.swigValue());
  }

  public GThreadPriority getPriority() {
    return GThreadPriority.swigToEnum(pangoJNI._GThread_priority_get(swigCPtr, this));
  }

  public _GThread() {
    this(pangoJNI.new__GThread(), true);
  }

}
