/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GTimeVal {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTimeVal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTimeVal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GTimeVal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTv_sec(int value) {
    pangoJNI._GTimeVal_tv_sec_set(swigCPtr, this, value);
  }

  public int getTv_sec() {
    return pangoJNI._GTimeVal_tv_sec_get(swigCPtr, this);
  }

  public void setTv_usec(int value) {
    pangoJNI._GTimeVal_tv_usec_set(swigCPtr, this, value);
  }

  public int getTv_usec() {
    return pangoJNI._GTimeVal_tv_usec_get(swigCPtr, this);
  }

  public _GTimeVal() {
    this(pangoJNI.new__GTimeVal(), true);
  }

}
