/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GTrashStack {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTrashStack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTrashStack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GTrashStack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(_GTrashStack value) {
    pangoJNI._GTrashStack_next_set(swigCPtr, this, _GTrashStack.getCPtr(value), value);
  }

  public _GTrashStack getNext() {
    long cPtr = pangoJNI._GTrashStack_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTrashStack(cPtr, false);
  }

  public _GTrashStack() {
    this(pangoJNI.new__GTrashStack(), true);
  }

}
