/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GTypeFundamentalInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTypeFundamentalInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTypeFundamentalInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GTypeFundamentalInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType_flags(GTypeFundamentalFlags value) {
    pangoJNI._GTypeFundamentalInfo_type_flags_set(swigCPtr, this, value.swigValue());
  }

  public GTypeFundamentalFlags getType_flags() {
    return GTypeFundamentalFlags.swigToEnum(pangoJNI._GTypeFundamentalInfo_type_flags_get(swigCPtr, this));
  }

  public _GTypeFundamentalInfo() {
    this(pangoJNI.new__GTypeFundamentalInfo(), true);
  }

}
