/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GTypeModule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTypeModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTypeModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GTypeModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GObject value) {
    pangoJNI._GTypeModule_parent_instance_set(swigCPtr, this, _GObject.getCPtr(value), value);
  }

  public _GObject getParent_instance() {
    long cPtr = pangoJNI._GTypeModule_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObject(cPtr, false);
  }

  public void setUse_count(long value) {
    pangoJNI._GTypeModule_use_count_set(swigCPtr, this, value);
  }

  public long getUse_count() {
    return pangoJNI._GTypeModule_use_count_get(swigCPtr, this);
  }

  public void setType_infos(_GSList value) {
    pangoJNI._GTypeModule_type_infos_set(swigCPtr, this, _GSList.getCPtr(value), value);
  }

  public _GSList getType_infos() {
    long cPtr = pangoJNI._GTypeModule_type_infos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSList(cPtr, false);
  }

  public void setInterface_infos(_GSList value) {
    pangoJNI._GTypeModule_interface_infos_set(swigCPtr, this, _GSList.getCPtr(value), value);
  }

  public _GSList getInterface_infos() {
    long cPtr = pangoJNI._GTypeModule_interface_infos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSList(cPtr, false);
  }

  public void setName(String value) {
    pangoJNI._GTypeModule_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return pangoJNI._GTypeModule_name_get(swigCPtr, this);
  }

  public _GTypeModule() {
    this(pangoJNI.new__GTypeModule(), true);
  }

}
