/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GTypeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTypeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTypeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GTypeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClass_size(int value) {
    pangoJNI._GTypeInfo_class_size_set(swigCPtr, this, value);
  }

  public int getClass_size() {
    return pangoJNI._GTypeInfo_class_size_get(swigCPtr, this);
  }

  public void setBase_init(SWIGTYPE_p_f_p_void__void value) {
    pangoJNI._GTypeInfo_base_init_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getBase_init() {
    long cPtr = pangoJNI._GTypeInfo_base_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setBase_finalize(SWIGTYPE_p_f_p_void__void value) {
    pangoJNI._GTypeInfo_base_finalize_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getBase_finalize() {
    long cPtr = pangoJNI._GTypeInfo_base_finalize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setClass_init(SWIGTYPE_p_f_p_void_p_void__void value) {
    pangoJNI._GTypeInfo_class_init_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__void getClass_init() {
    long cPtr = pangoJNI._GTypeInfo_class_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__void(cPtr, false);
  }

  public void setClass_finalize(SWIGTYPE_p_f_p_void_p_void__void value) {
    pangoJNI._GTypeInfo_class_finalize_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__void getClass_finalize() {
    long cPtr = pangoJNI._GTypeInfo_class_finalize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__void(cPtr, false);
  }

  public void setClass_data(SWIGTYPE_p_void value) {
    pangoJNI._GTypeInfo_class_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getClass_data() {
    long cPtr = pangoJNI._GTypeInfo_class_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setInstance_size(int value) {
    pangoJNI._GTypeInfo_instance_size_set(swigCPtr, this, value);
  }

  public int getInstance_size() {
    return pangoJNI._GTypeInfo_instance_size_get(swigCPtr, this);
  }

  public void setN_preallocs(int value) {
    pangoJNI._GTypeInfo_n_preallocs_set(swigCPtr, this, value);
  }

  public int getN_preallocs() {
    return pangoJNI._GTypeInfo_n_preallocs_get(swigCPtr, this);
  }

  public void setInstance_init(SWIGTYPE_p_f_p_struct__GTypeInstance_p_void__void value) {
    pangoJNI._GTypeInfo_instance_init_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GTypeInstance_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GTypeInstance_p_void__void getInstance_init() {
    long cPtr = pangoJNI._GTypeInfo_instance_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GTypeInstance_p_void__void(cPtr, false);
  }

  public void setValue_table(_GTypeValueTable value) {
    pangoJNI._GTypeInfo_value_table_set(swigCPtr, this, _GTypeValueTable.getCPtr(value), value);
  }

  public _GTypeValueTable getValue_table() {
    long cPtr = pangoJNI._GTypeInfo_value_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeValueTable(cPtr, false);
  }

  public _GTypeInfo() {
    this(pangoJNI.new__GTypeInfo(), true);
  }

}
