/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GTypeModuleClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTypeModuleClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTypeModuleClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GTypeModuleClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    pangoJNI._GTypeModuleClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = pangoJNI._GTypeModuleClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setLoad(SWIGTYPE_p_f_p_struct__GTypeModule__int value) {
    pangoJNI._GTypeModuleClass_load_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GTypeModule__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GTypeModule__int getLoad() {
    long cPtr = pangoJNI._GTypeModuleClass_load_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GTypeModule__int(cPtr, false);
  }

  public void setUnload(SWIGTYPE_p_f_p_struct__GTypeModule__void value) {
    pangoJNI._GTypeModuleClass_unload_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__GTypeModule__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__GTypeModule__void getUnload() {
    long cPtr = pangoJNI._GTypeModuleClass_unload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__GTypeModule__void(cPtr, false);
  }

  public void setReserved1(SWIGTYPE_p_f_void__void value) {
    pangoJNI._GTypeModuleClass_reserved1_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getReserved1() {
    long cPtr = pangoJNI._GTypeModuleClass_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setReserved2(SWIGTYPE_p_f_void__void value) {
    pangoJNI._GTypeModuleClass_reserved2_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getReserved2() {
    long cPtr = pangoJNI._GTypeModuleClass_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setReserved3(SWIGTYPE_p_f_void__void value) {
    pangoJNI._GTypeModuleClass_reserved3_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getReserved3() {
    long cPtr = pangoJNI._GTypeModuleClass_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setReserved4(SWIGTYPE_p_f_void__void value) {
    pangoJNI._GTypeModuleClass_reserved4_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getReserved4() {
    long cPtr = pangoJNI._GTypeModuleClass_reserved4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public _GTypeModuleClass() {
    this(pangoJNI.new__GTypeModuleClass(), true);
  }

}
