/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GValueArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GValueArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GValueArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GValueArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN_values(long value) {
    pangoJNI._GValueArray_n_values_set(swigCPtr, this, value);
  }

  public long getN_values() {
    return pangoJNI._GValueArray_n_values_get(swigCPtr, this);
  }

  public void setValues(_GValue value) {
    pangoJNI._GValueArray_values_set(swigCPtr, this, _GValue.getCPtr(value), value);
  }

  public _GValue getValues() {
    long cPtr = pangoJNI._GValueArray_values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GValue(cPtr, false);
  }

  public void setN_prealloced(long value) {
    pangoJNI._GValueArray_n_prealloced_set(swigCPtr, this, value);
  }

  public long getN_prealloced() {
    return pangoJNI._GValueArray_n_prealloced_get(swigCPtr, this);
  }

  public _GValueArray() {
    this(pangoJNI.new__GValueArray(), true);
  }

}
