/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GVariantDict {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GVariantDict(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GVariantDict obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GVariantDict(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public _GVariantDict_u getU() {
    long cPtr = pangoJNI._GVariantDict_u_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GVariantDict_u(cPtr, false);
  }

  public _GVariantDict() {
    this(pangoJNI.new__GVariantDict(), true);
  }

}
