/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _GVariantBuilder_u_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GVariantBuilder_u_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GVariantBuilder_u_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__GVariantBuilder_u_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPartial_magic(java.math.BigInteger value) {
    pangoJNI._GVariantBuilder_u_s_partial_magic_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getPartial_magic() {
    return pangoJNI._GVariantBuilder_u_s_partial_magic_get(swigCPtr, this);
  }

  public void setType(SWIGTYPE_p__GVariantType value) {
    pangoJNI._GVariantBuilder_u_s_type_set(swigCPtr, this, SWIGTYPE_p__GVariantType.getCPtr(value));
  }

  public SWIGTYPE_p__GVariantType getType() {
    long cPtr = pangoJNI._GVariantBuilder_u_s_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GVariantType(cPtr, false);
  }

  public void setY(SWIGTYPE_p_unsigned_long_long value) {
    pangoJNI._GVariantBuilder_u_s_y_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getY() {
    long cPtr = pangoJNI._GVariantBuilder_u_s_y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public _GVariantBuilder_u_s() {
    this(pangoJNI.new__GVariantBuilder_u_s(), true);
  }

}
