/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoMatrix {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoMatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXx(double value) {
    pangoJNI._PangoMatrix_xx_set(swigCPtr, this, value);
  }

  public double getXx() {
    return pangoJNI._PangoMatrix_xx_get(swigCPtr, this);
  }

  public void setXy(double value) {
    pangoJNI._PangoMatrix_xy_set(swigCPtr, this, value);
  }

  public double getXy() {
    return pangoJNI._PangoMatrix_xy_get(swigCPtr, this);
  }

  public void setYx(double value) {
    pangoJNI._PangoMatrix_yx_set(swigCPtr, this, value);
  }

  public double getYx() {
    return pangoJNI._PangoMatrix_yx_get(swigCPtr, this);
  }

  public void setYy(double value) {
    pangoJNI._PangoMatrix_yy_set(swigCPtr, this, value);
  }

  public double getYy() {
    return pangoJNI._PangoMatrix_yy_get(swigCPtr, this);
  }

  public void setX0(double value) {
    pangoJNI._PangoMatrix_x0_set(swigCPtr, this, value);
  }

  public double getX0() {
    return pangoJNI._PangoMatrix_x0_get(swigCPtr, this);
  }

  public void setY0(double value) {
    pangoJNI._PangoMatrix_y0_set(swigCPtr, this, value);
  }

  public double getY0() {
    return pangoJNI._PangoMatrix_y0_get(swigCPtr, this);
  }

  public _PangoMatrix() {
    this(pangoJNI.new__PangoMatrix(), true);
  }

}
