/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoAttrSize {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoAttrSize(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoAttrSize obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoAttrSize(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttr(_PangoAttribute value) {
    pangoJNI._PangoAttrSize_attr_set(swigCPtr, this, _PangoAttribute.getCPtr(value), value);
  }

  public _PangoAttribute getAttr() {
    long cPtr = pangoJNI._PangoAttrSize_attr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoAttribute(cPtr, false);
  }

  public void setSize(int value) {
    pangoJNI._PangoAttrSize_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return pangoJNI._PangoAttrSize_size_get(swigCPtr, this);
  }

  public void setAbsolute(long value) {
    pangoJNI._PangoAttrSize_absolute_set(swigCPtr, this, value);
  }

  public long getAbsolute() {
    return pangoJNI._PangoAttrSize_absolute_get(swigCPtr, this);
  }

  public _PangoAttrSize() {
    this(pangoJNI.new__PangoAttrSize(), true);
  }

}
