/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoAnalysis {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoAnalysis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoAnalysis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoAnalysis(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setShape_engine(SWIGTYPE_p__PangoEngineShape value) {
    pangoJNI._PangoAnalysis_shape_engine_set(swigCPtr, this, SWIGTYPE_p__PangoEngineShape.getCPtr(value));
  }

  public SWIGTYPE_p__PangoEngineShape getShape_engine() {
    long cPtr = pangoJNI._PangoAnalysis_shape_engine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoEngineShape(cPtr, false);
  }

  public void setLang_engine(SWIGTYPE_p__PangoEngineLang value) {
    pangoJNI._PangoAnalysis_lang_engine_set(swigCPtr, this, SWIGTYPE_p__PangoEngineLang.getCPtr(value));
  }

  public SWIGTYPE_p__PangoEngineLang getLang_engine() {
    long cPtr = pangoJNI._PangoAnalysis_lang_engine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoEngineLang(cPtr, false);
  }

  public void setFont(SWIGTYPE_p__PangoFont value) {
    pangoJNI._PangoAnalysis_font_set(swigCPtr, this, SWIGTYPE_p__PangoFont.getCPtr(value));
  }

  public SWIGTYPE_p__PangoFont getFont() {
    long cPtr = pangoJNI._PangoAnalysis_font_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoFont(cPtr, false);
  }

  public void setLevel(short value) {
    pangoJNI._PangoAnalysis_level_set(swigCPtr, this, value);
  }

  public short getLevel() {
    return pangoJNI._PangoAnalysis_level_get(swigCPtr, this);
  }

  public void setGravity(short value) {
    pangoJNI._PangoAnalysis_gravity_set(swigCPtr, this, value);
  }

  public short getGravity() {
    return pangoJNI._PangoAnalysis_gravity_get(swigCPtr, this);
  }

  public void setFlags(short value) {
    pangoJNI._PangoAnalysis_flags_set(swigCPtr, this, value);
  }

  public short getFlags() {
    return pangoJNI._PangoAnalysis_flags_get(swigCPtr, this);
  }

  public void setScript(short value) {
    pangoJNI._PangoAnalysis_script_set(swigCPtr, this, value);
  }

  public short getScript() {
    return pangoJNI._PangoAnalysis_script_get(swigCPtr, this);
  }

  public void setLanguage(SWIGTYPE_p__PangoLanguage value) {
    pangoJNI._PangoAnalysis_language_set(swigCPtr, this, SWIGTYPE_p__PangoLanguage.getCPtr(value));
  }

  public SWIGTYPE_p__PangoLanguage getLanguage() {
    long cPtr = pangoJNI._PangoAnalysis_language_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoLanguage(cPtr, false);
  }

  public void setExtra_attrs(_GSList value) {
    pangoJNI._PangoAnalysis_extra_attrs_set(swigCPtr, this, _GSList.getCPtr(value), value);
  }

  public _GSList getExtra_attrs() {
    long cPtr = pangoJNI._PangoAnalysis_extra_attrs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSList(cPtr, false);
  }

  public _PangoAnalysis() {
    this(pangoJNI.new__PangoAnalysis(), true);
  }

}
