/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoAttrLanguage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoAttrLanguage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoAttrLanguage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoAttrLanguage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttr(_PangoAttribute value) {
    pangoJNI._PangoAttrLanguage_attr_set(swigCPtr, this, _PangoAttribute.getCPtr(value), value);
  }

  public _PangoAttribute getAttr() {
    long cPtr = pangoJNI._PangoAttrLanguage_attr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoAttribute(cPtr, false);
  }

  public void setValue(SWIGTYPE_p__PangoLanguage value) {
    pangoJNI._PangoAttrLanguage_value_set(swigCPtr, this, SWIGTYPE_p__PangoLanguage.getCPtr(value));
  }

  public SWIGTYPE_p__PangoLanguage getValue() {
    long cPtr = pangoJNI._PangoAttrLanguage_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoLanguage(cPtr, false);
  }

  public _PangoAttrLanguage() {
    this(pangoJNI.new__PangoAttrLanguage(), true);
  }

}
