/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoGlyphVisAttr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoGlyphVisAttr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoGlyphVisAttr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoGlyphVisAttr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIs_cluster_start(long value) {
    pangoJNI._PangoGlyphVisAttr_is_cluster_start_set(swigCPtr, this, value);
  }

  public long getIs_cluster_start() {
    return pangoJNI._PangoGlyphVisAttr_is_cluster_start_get(swigCPtr, this);
  }

  public _PangoGlyphVisAttr() {
    this(pangoJNI.new__PangoGlyphVisAttr(), true);
  }

}
