/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRed(int value) {
    pangoJNI._PangoColor_red_set(swigCPtr, this, value);
  }

  public int getRed() {
    return pangoJNI._PangoColor_red_get(swigCPtr, this);
  }

  public void setGreen(int value) {
    pangoJNI._PangoColor_green_set(swigCPtr, this, value);
  }

  public int getGreen() {
    return pangoJNI._PangoColor_green_get(swigCPtr, this);
  }

  public void setBlue(int value) {
    pangoJNI._PangoColor_blue_set(swigCPtr, this, value);
  }

  public int getBlue() {
    return pangoJNI._PangoColor_blue_get(swigCPtr, this);
  }

  public _PangoColor() {
    this(pangoJNI.new__PangoColor(), true);
  }

}
