/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoAttrClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoAttrClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoAttrClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoAttrClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(PangoAttrType value) {
    pangoJNI._PangoAttrClass_type_set(swigCPtr, this, value.swigValue());
  }

  public PangoAttrType getType() {
    return PangoAttrType.swigToEnum(pangoJNI._PangoAttrClass_type_get(swigCPtr, this));
  }

  public void setCopy(SWIGTYPE_p_f_p_q_const__PangoAttribute__p__PangoAttribute value) {
    pangoJNI._PangoAttrClass_copy_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__PangoAttribute__p__PangoAttribute.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__PangoAttribute__p__PangoAttribute getCopy() {
    long cPtr = pangoJNI._PangoAttrClass_copy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__PangoAttribute__p__PangoAttribute(cPtr, false);
  }

  public void setDestroy(SWIGTYPE_p_f_p_struct__PangoAttribute__void value) {
    pangoJNI._PangoAttrClass_destroy_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoAttribute__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoAttribute__void getDestroy() {
    long cPtr = pangoJNI._PangoAttrClass_destroy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoAttribute__void(cPtr, false);
  }

  public void setEqual(SWIGTYPE_p_f_p_q_const__struct__PangoAttribute_p_q_const__struct__PangoAttribute__int value) {
    pangoJNI._PangoAttrClass_equal_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__struct__PangoAttribute_p_q_const__struct__PangoAttribute__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__struct__PangoAttribute_p_q_const__struct__PangoAttribute__int getEqual() {
    long cPtr = pangoJNI._PangoAttrClass_equal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__struct__PangoAttribute_p_q_const__struct__PangoAttribute__int(cPtr, false);
  }

  public _PangoAttrClass() {
    this(pangoJNI.new__PangoAttrClass(), true);
  }

}
