/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoGlyphInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoGlyphInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoGlyphInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoGlyphInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGlyph(long value) {
    pangoJNI._PangoGlyphInfo_glyph_set(swigCPtr, this, value);
  }

  public long getGlyph() {
    return pangoJNI._PangoGlyphInfo_glyph_get(swigCPtr, this);
  }

  public void setGeometry(_PangoGlyphGeometry value) {
    pangoJNI._PangoGlyphInfo_geometry_set(swigCPtr, this, _PangoGlyphGeometry.getCPtr(value), value);
  }

  public _PangoGlyphGeometry getGeometry() {
    long cPtr = pangoJNI._PangoGlyphInfo_geometry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoGlyphGeometry(cPtr, false);
  }

  public void setAttr(_PangoGlyphVisAttr value) {
    pangoJNI._PangoGlyphInfo_attr_set(swigCPtr, this, _PangoGlyphVisAttr.getCPtr(value), value);
  }

  public _PangoGlyphVisAttr getAttr() {
    long cPtr = pangoJNI._PangoGlyphInfo_attr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoGlyphVisAttr(cPtr, false);
  }

  public _PangoGlyphInfo() {
    this(pangoJNI.new__PangoGlyphInfo(), true);
  }

}
