/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoRendererClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoRendererClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoRendererClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoRendererClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    pangoJNI._PangoRendererClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = pangoJNI._PangoRendererClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setDraw_glyphs(SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_p_struct__PangoGlyphString_int_int__void value) {
    pangoJNI._PangoRendererClass_draw_glyphs_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_p_struct__PangoGlyphString_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_p_struct__PangoGlyphString_int_int__void getDraw_glyphs() {
    long cPtr = pangoJNI._PangoRendererClass_draw_glyphs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_p_struct__PangoGlyphString_int_int__void(cPtr, false);
  }

  public void setDraw_rectangle(SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_int_int_int_int__void value) {
    pangoJNI._PangoRendererClass_draw_rectangle_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_int_int_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_int_int_int_int__void getDraw_rectangle() {
    long cPtr = pangoJNI._PangoRendererClass_draw_rectangle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_int_int_int_int__void(cPtr, false);
  }

  public void setDraw_error_underline(SWIGTYPE_p_f_p_struct__PangoRenderer_int_int_int_int__void value) {
    pangoJNI._PangoRendererClass_draw_error_underline_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_int_int_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_int_int_int_int__void getDraw_error_underline() {
    long cPtr = pangoJNI._PangoRendererClass_draw_error_underline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_int_int_int_int__void(cPtr, false);
  }

  public void setDraw_shape(SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoAttrShape_int_int__void value) {
    pangoJNI._PangoRendererClass_draw_shape_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoAttrShape_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoAttrShape_int_int__void getDraw_shape() {
    long cPtr = pangoJNI._PangoRendererClass_draw_shape_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoAttrShape_int_int__void(cPtr, false);
  }

  public void setDraw_trapezoid(SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_double_double_double_double_double_double__void value) {
    pangoJNI._PangoRendererClass_draw_trapezoid_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_double_double_double_double_double_double__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_double_double_double_double_double_double__void getDraw_trapezoid() {
    long cPtr = pangoJNI._PangoRendererClass_draw_trapezoid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart_double_double_double_double_double_double__void(cPtr, false);
  }

  public void setDraw_glyph(SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_unsigned_int_double_double__void value) {
    pangoJNI._PangoRendererClass_draw_glyph_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_unsigned_int_double_double__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_unsigned_int_double_double__void getDraw_glyph() {
    long cPtr = pangoJNI._PangoRendererClass_draw_glyph_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoFont_unsigned_int_double_double__void(cPtr, false);
  }

  public void setPart_changed(SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart__void value) {
    pangoJNI._PangoRendererClass_part_changed_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart__void getPart_changed() {
    long cPtr = pangoJNI._PangoRendererClass_part_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_enum_PangoRenderPart__void(cPtr, false);
  }

  public void setBegin(SWIGTYPE_p_f_p_struct__PangoRenderer__void value) {
    pangoJNI._PangoRendererClass_begin_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer__void getBegin() {
    long cPtr = pangoJNI._PangoRendererClass_begin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer__void(cPtr, false);
  }

  public void setEnd(SWIGTYPE_p_f_p_struct__PangoRenderer__void value) {
    pangoJNI._PangoRendererClass_end_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer__void getEnd() {
    long cPtr = pangoJNI._PangoRendererClass_end_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer__void(cPtr, false);
  }

  public void setPrepare_run(SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoGlyphItem__void value) {
    pangoJNI._PangoRendererClass_prepare_run_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoGlyphItem__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoGlyphItem__void getPrepare_run() {
    long cPtr = pangoJNI._PangoRendererClass_prepare_run_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_p_struct__PangoGlyphItem__void(cPtr, false);
  }

  public void setDraw_glyph_item(SWIGTYPE_p_f_p_struct__PangoRenderer_p_q_const__char_p_struct__PangoGlyphItem_int_int__void value) {
    pangoJNI._PangoRendererClass_draw_glyph_item_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__PangoRenderer_p_q_const__char_p_struct__PangoGlyphItem_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__PangoRenderer_p_q_const__char_p_struct__PangoGlyphItem_int_int__void getDraw_glyph_item() {
    long cPtr = pangoJNI._PangoRendererClass_draw_glyph_item_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__PangoRenderer_p_q_const__char_p_struct__PangoGlyphItem_int_int__void(cPtr, false);
  }

  public void set_pango_reserved2(SWIGTYPE_p_f_void__void value) {
    pangoJNI._PangoRendererClass__pango_reserved2_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_pango_reserved2() {
    long cPtr = pangoJNI._PangoRendererClass__pango_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_pango_reserved3(SWIGTYPE_p_f_void__void value) {
    pangoJNI._PangoRendererClass__pango_reserved3_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_pango_reserved3() {
    long cPtr = pangoJNI._PangoRendererClass__pango_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_pango_reserved4(SWIGTYPE_p_f_void__void value) {
    pangoJNI._PangoRendererClass__pango_reserved4_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_pango_reserved4() {
    long cPtr = pangoJNI._PangoRendererClass__pango_reserved4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public _PangoRendererClass() {
    this(pangoJNI.new__PangoRendererClass(), true);
  }

}
