/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoRenderer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoRenderer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoRenderer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoRenderer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GObject value) {
    pangoJNI._PangoRenderer_parent_instance_set(swigCPtr, this, _GObject.getCPtr(value), value);
  }

  public _GObject getParent_instance() {
    long cPtr = pangoJNI._PangoRenderer_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObject(cPtr, false);
  }

  public void setUnderline(PangoUnderline value) {
    pangoJNI._PangoRenderer_underline_set(swigCPtr, this, value.swigValue());
  }

  public PangoUnderline getUnderline() {
    return PangoUnderline.swigToEnum(pangoJNI._PangoRenderer_underline_get(swigCPtr, this));
  }

  public void setStrikethrough(int value) {
    pangoJNI._PangoRenderer_strikethrough_set(swigCPtr, this, value);
  }

  public int getStrikethrough() {
    return pangoJNI._PangoRenderer_strikethrough_get(swigCPtr, this);
  }

  public void setActive_count(int value) {
    pangoJNI._PangoRenderer_active_count_set(swigCPtr, this, value);
  }

  public int getActive_count() {
    return pangoJNI._PangoRenderer_active_count_get(swigCPtr, this);
  }

  public void setMatrix(_PangoMatrix value) {
    pangoJNI._PangoRenderer_matrix_set(swigCPtr, this, _PangoMatrix.getCPtr(value), value);
  }

  public _PangoMatrix getMatrix() {
    long cPtr = pangoJNI._PangoRenderer_matrix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoMatrix(cPtr, false);
  }

  public void setPriv(SWIGTYPE_p__PangoRendererPrivate value) {
    pangoJNI._PangoRenderer_priv_set(swigCPtr, this, SWIGTYPE_p__PangoRendererPrivate.getCPtr(value));
  }

  public SWIGTYPE_p__PangoRendererPrivate getPriv() {
    long cPtr = pangoJNI._PangoRenderer_priv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoRendererPrivate(cPtr, false);
  }

  public _PangoRenderer() {
    this(pangoJNI.new__PangoRenderer(), true);
  }

}
