/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoAttrColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoAttrColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoAttrColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoAttrColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttr(_PangoAttribute value) {
    pangoJNI._PangoAttrColor_attr_set(swigCPtr, this, _PangoAttribute.getCPtr(value), value);
  }

  public _PangoAttribute getAttr() {
    long cPtr = pangoJNI._PangoAttrColor_attr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoAttribute(cPtr, false);
  }

  public void setColor(_PangoColor value) {
    pangoJNI._PangoAttrColor_color_set(swigCPtr, this, _PangoColor.getCPtr(value), value);
  }

  public _PangoColor getColor() {
    long cPtr = pangoJNI._PangoAttrColor_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoColor(cPtr, false);
  }

  public _PangoAttrColor() {
    this(pangoJNI.new__PangoAttrColor(), true);
  }

}
