/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoAttrFontDesc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoAttrFontDesc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoAttrFontDesc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoAttrFontDesc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAttr(_PangoAttribute value) {
    pangoJNI._PangoAttrFontDesc_attr_set(swigCPtr, this, _PangoAttribute.getCPtr(value), value);
  }

  public _PangoAttribute getAttr() {
    long cPtr = pangoJNI._PangoAttrFontDesc_attr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoAttribute(cPtr, false);
  }

  public void setDesc(SWIGTYPE_p__PangoFontDescription value) {
    pangoJNI._PangoAttrFontDesc_desc_set(swigCPtr, this, SWIGTYPE_p__PangoFontDescription.getCPtr(value));
  }

  public SWIGTYPE_p__PangoFontDescription getDesc() {
    long cPtr = pangoJNI._PangoAttrFontDesc_desc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__PangoFontDescription(cPtr, false);
  }

  public _PangoAttrFontDesc() {
    this(pangoJNI.new__PangoAttrFontDesc(), true);
  }

}
