/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoItem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOffset(int value) {
    pangoJNI._PangoItem_offset_set(swigCPtr, this, value);
  }

  public int getOffset() {
    return pangoJNI._PangoItem_offset_get(swigCPtr, this);
  }

  public void setLength(int value) {
    pangoJNI._PangoItem_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return pangoJNI._PangoItem_length_get(swigCPtr, this);
  }

  public void setNum_chars(int value) {
    pangoJNI._PangoItem_num_chars_set(swigCPtr, this, value);
  }

  public int getNum_chars() {
    return pangoJNI._PangoItem_num_chars_get(swigCPtr, this);
  }

  public void setAnalysis(_PangoAnalysis value) {
    pangoJNI._PangoItem_analysis_set(swigCPtr, this, _PangoAnalysis.getCPtr(value), value);
  }

  public _PangoAnalysis getAnalysis() {
    long cPtr = pangoJNI._PangoItem_analysis_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _PangoAnalysis(cPtr, false);
  }

  public _PangoItem() {
    this(pangoJNI.new__PangoItem(), true);
  }

}
