/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class _PangoRectangle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PangoRectangle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PangoRectangle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete__PangoRectangle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    pangoJNI._PangoRectangle_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return pangoJNI._PangoRectangle_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    pangoJNI._PangoRectangle_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return pangoJNI._PangoRectangle_y_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    pangoJNI._PangoRectangle_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return pangoJNI._PangoRectangle_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    pangoJNI._PangoRectangle_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return pangoJNI._PangoRectangle_height_get(swigCPtr, this);
  }

  public _PangoRectangle() {
    this(pangoJNI.new__PangoRectangle(), true);
  }

}
