/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class cairo_matrix_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cairo_matrix_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cairo_matrix_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cairoJNI.delete_cairo_matrix_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXx(double value) {
    cairoJNI.cairo_matrix_t_xx_set(swigCPtr, this, value);
  }

  public double getXx() {
    return cairoJNI.cairo_matrix_t_xx_get(swigCPtr, this);
  }

  public void setYx(double value) {
    cairoJNI.cairo_matrix_t_yx_set(swigCPtr, this, value);
  }

  public double getYx() {
    return cairoJNI.cairo_matrix_t_yx_get(swigCPtr, this);
  }

  public void setXy(double value) {
    cairoJNI.cairo_matrix_t_xy_set(swigCPtr, this, value);
  }

  public double getXy() {
    return cairoJNI.cairo_matrix_t_xy_get(swigCPtr, this);
  }

  public void setYy(double value) {
    cairoJNI.cairo_matrix_t_yy_set(swigCPtr, this, value);
  }

  public double getYy() {
    return cairoJNI.cairo_matrix_t_yy_get(swigCPtr, this);
  }

  public void setX0(double value) {
    cairoJNI.cairo_matrix_t_x0_set(swigCPtr, this, value);
  }

  public double getX0() {
    return cairoJNI.cairo_matrix_t_x0_get(swigCPtr, this);
  }

  public void setY0(double value) {
    cairoJNI.cairo_matrix_t_y0_set(swigCPtr, this, value);
  }

  public double getY0() {
    return cairoJNI.cairo_matrix_t_y0_get(swigCPtr, this);
  }

  public cairo_matrix_t() {
    this(cairoJNI.new_cairo_matrix_t(), true);
  }

}
