/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_surface_type_t {
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_IMAGE = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_IMAGE");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_PDF = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_PDF");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_PS = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_PS");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_XLIB = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_XLIB");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_XCB = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_XCB");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_GLITZ = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_GLITZ");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_QUARTZ = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_QUARTZ");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_WIN32 = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_WIN32");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_BEOS = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_BEOS");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_DIRECTFB = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_DIRECTFB");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_SVG = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_SVG");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_OS2 = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_OS2");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_WIN32_PRINTING = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_WIN32_PRINTING");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_QUARTZ_IMAGE = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_QUARTZ_IMAGE");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_SCRIPT = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_SCRIPT");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_QT = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_QT");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_RECORDING = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_RECORDING");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_VG = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_VG");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_GL = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_GL");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_DRM = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_DRM");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_TEE = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_TEE");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_XML = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_XML");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_SKIA = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_SKIA");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_SUBSURFACE = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_SUBSURFACE");
  public final static cairo_surface_type_t CAIRO_SURFACE_TYPE_COGL = new cairo_surface_type_t("CAIRO_SURFACE_TYPE_COGL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_surface_type_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_surface_type_t.class + " with value " + swigValue);
  }

  private cairo_surface_type_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_surface_type_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_surface_type_t(String swigName, cairo_surface_type_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_surface_type_t[] swigValues = { CAIRO_SURFACE_TYPE_IMAGE, CAIRO_SURFACE_TYPE_PDF, CAIRO_SURFACE_TYPE_PS, CAIRO_SURFACE_TYPE_XLIB, CAIRO_SURFACE_TYPE_XCB, CAIRO_SURFACE_TYPE_GLITZ, CAIRO_SURFACE_TYPE_QUARTZ, CAIRO_SURFACE_TYPE_WIN32, CAIRO_SURFACE_TYPE_BEOS, CAIRO_SURFACE_TYPE_DIRECTFB, CAIRO_SURFACE_TYPE_SVG, CAIRO_SURFACE_TYPE_OS2, CAIRO_SURFACE_TYPE_WIN32_PRINTING, CAIRO_SURFACE_TYPE_QUARTZ_IMAGE, CAIRO_SURFACE_TYPE_SCRIPT, CAIRO_SURFACE_TYPE_QT, CAIRO_SURFACE_TYPE_RECORDING, CAIRO_SURFACE_TYPE_VG, CAIRO_SURFACE_TYPE_GL, CAIRO_SURFACE_TYPE_DRM, CAIRO_SURFACE_TYPE_TEE, CAIRO_SURFACE_TYPE_XML, CAIRO_SURFACE_TYPE_SKIA, CAIRO_SURFACE_TYPE_SUBSURFACE, CAIRO_SURFACE_TYPE_COGL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

