/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class cairo_user_data_key_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cairo_user_data_key_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cairo_user_data_key_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete_cairo_user_data_key_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUnused(int value) {
    pangoJNI.cairo_user_data_key_t_unused_set(swigCPtr, this, value);
  }

  public int getUnused() {
    return pangoJNI.cairo_user_data_key_t_unused_get(swigCPtr, this);
  }

  public cairo_user_data_key_t() {
    this(pangoJNI.new_cairo_user_data_key_t(), true);
  }

}
