/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_pattern_type_t {
  public final static cairo_pattern_type_t CAIRO_PATTERN_TYPE_SOLID = new cairo_pattern_type_t("CAIRO_PATTERN_TYPE_SOLID");
  public final static cairo_pattern_type_t CAIRO_PATTERN_TYPE_SURFACE = new cairo_pattern_type_t("CAIRO_PATTERN_TYPE_SURFACE");
  public final static cairo_pattern_type_t CAIRO_PATTERN_TYPE_LINEAR = new cairo_pattern_type_t("CAIRO_PATTERN_TYPE_LINEAR");
  public final static cairo_pattern_type_t CAIRO_PATTERN_TYPE_RADIAL = new cairo_pattern_type_t("CAIRO_PATTERN_TYPE_RADIAL");
  public final static cairo_pattern_type_t CAIRO_PATTERN_TYPE_MESH = new cairo_pattern_type_t("CAIRO_PATTERN_TYPE_MESH");
  public final static cairo_pattern_type_t CAIRO_PATTERN_TYPE_RASTER_SOURCE = new cairo_pattern_type_t("CAIRO_PATTERN_TYPE_RASTER_SOURCE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_pattern_type_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_pattern_type_t.class + " with value " + swigValue);
  }

  private cairo_pattern_type_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_pattern_type_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_pattern_type_t(String swigName, cairo_pattern_type_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_pattern_type_t[] swigValues = { CAIRO_PATTERN_TYPE_SOLID, CAIRO_PATTERN_TYPE_SURFACE, CAIRO_PATTERN_TYPE_LINEAR, CAIRO_PATTERN_TYPE_RADIAL, CAIRO_PATTERN_TYPE_MESH, CAIRO_PATTERN_TYPE_RASTER_SOURCE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

