/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_content_t {
  public final static cairo_content_t CAIRO_CONTENT_COLOR = new cairo_content_t("CAIRO_CONTENT_COLOR", pangoJNI.CAIRO_CONTENT_COLOR_get());
  public final static cairo_content_t CAIRO_CONTENT_ALPHA = new cairo_content_t("CAIRO_CONTENT_ALPHA", pangoJNI.CAIRO_CONTENT_ALPHA_get());
  public final static cairo_content_t CAIRO_CONTENT_COLOR_ALPHA = new cairo_content_t("CAIRO_CONTENT_COLOR_ALPHA", pangoJNI.CAIRO_CONTENT_COLOR_ALPHA_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_content_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_content_t.class + " with value " + swigValue);
  }

  private cairo_content_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_content_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_content_t(String swigName, cairo_content_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_content_t[] swigValues = { CAIRO_CONTENT_COLOR, CAIRO_CONTENT_ALPHA, CAIRO_CONTENT_COLOR_ALPHA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

