/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_subpixel_order_t {
  public final static cairo_subpixel_order_t CAIRO_SUBPIXEL_ORDER_DEFAULT = new cairo_subpixel_order_t("CAIRO_SUBPIXEL_ORDER_DEFAULT");
  public final static cairo_subpixel_order_t CAIRO_SUBPIXEL_ORDER_RGB = new cairo_subpixel_order_t("CAIRO_SUBPIXEL_ORDER_RGB");
  public final static cairo_subpixel_order_t CAIRO_SUBPIXEL_ORDER_BGR = new cairo_subpixel_order_t("CAIRO_SUBPIXEL_ORDER_BGR");
  public final static cairo_subpixel_order_t CAIRO_SUBPIXEL_ORDER_VRGB = new cairo_subpixel_order_t("CAIRO_SUBPIXEL_ORDER_VRGB");
  public final static cairo_subpixel_order_t CAIRO_SUBPIXEL_ORDER_VBGR = new cairo_subpixel_order_t("CAIRO_SUBPIXEL_ORDER_VBGR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_subpixel_order_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_subpixel_order_t.class + " with value " + swigValue);
  }

  private cairo_subpixel_order_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_subpixel_order_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_subpixel_order_t(String swigName, cairo_subpixel_order_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_subpixel_order_t[] swigValues = { CAIRO_SUBPIXEL_ORDER_DEFAULT, CAIRO_SUBPIXEL_ORDER_RGB, CAIRO_SUBPIXEL_ORDER_BGR, CAIRO_SUBPIXEL_ORDER_VRGB, CAIRO_SUBPIXEL_ORDER_VBGR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

