/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_extend_t {
  public final static cairo_extend_t CAIRO_EXTEND_NONE = new cairo_extend_t("CAIRO_EXTEND_NONE");
  public final static cairo_extend_t CAIRO_EXTEND_REPEAT = new cairo_extend_t("CAIRO_EXTEND_REPEAT");
  public final static cairo_extend_t CAIRO_EXTEND_REFLECT = new cairo_extend_t("CAIRO_EXTEND_REFLECT");
  public final static cairo_extend_t CAIRO_EXTEND_PAD = new cairo_extend_t("CAIRO_EXTEND_PAD");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_extend_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_extend_t.class + " with value " + swigValue);
  }

  private cairo_extend_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_extend_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_extend_t(String swigName, cairo_extend_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_extend_t[] swigValues = { CAIRO_EXTEND_NONE, CAIRO_EXTEND_REPEAT, CAIRO_EXTEND_REFLECT, CAIRO_EXTEND_PAD };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

