/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_format_t {
  public final static cairo_format_t CAIRO_FORMAT_INVALID = new cairo_format_t("CAIRO_FORMAT_INVALID", cairoJNI.CAIRO_FORMAT_INVALID_get());
  public final static cairo_format_t CAIRO_FORMAT_ARGB32 = new cairo_format_t("CAIRO_FORMAT_ARGB32", cairoJNI.CAIRO_FORMAT_ARGB32_get());
  public final static cairo_format_t CAIRO_FORMAT_RGB24 = new cairo_format_t("CAIRO_FORMAT_RGB24", cairoJNI.CAIRO_FORMAT_RGB24_get());
  public final static cairo_format_t CAIRO_FORMAT_A8 = new cairo_format_t("CAIRO_FORMAT_A8", cairoJNI.CAIRO_FORMAT_A8_get());
  public final static cairo_format_t CAIRO_FORMAT_A1 = new cairo_format_t("CAIRO_FORMAT_A1", cairoJNI.CAIRO_FORMAT_A1_get());
  public final static cairo_format_t CAIRO_FORMAT_RGB16_565 = new cairo_format_t("CAIRO_FORMAT_RGB16_565", cairoJNI.CAIRO_FORMAT_RGB16_565_get());
  public final static cairo_format_t CAIRO_FORMAT_RGB30 = new cairo_format_t("CAIRO_FORMAT_RGB30", cairoJNI.CAIRO_FORMAT_RGB30_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_format_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_format_t.class + " with value " + swigValue);
  }

  private cairo_format_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_format_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_format_t(String swigName, cairo_format_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_format_t[] swigValues = { CAIRO_FORMAT_INVALID, CAIRO_FORMAT_ARGB32, CAIRO_FORMAT_RGB24, CAIRO_FORMAT_A8, CAIRO_FORMAT_A1, CAIRO_FORMAT_RGB16_565, CAIRO_FORMAT_RGB30 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

