/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class cairo_status_t {
  public final static cairo_status_t CAIRO_STATUS_SUCCESS = new cairo_status_t("CAIRO_STATUS_SUCCESS", cairoJNI.CAIRO_STATUS_SUCCESS_get());
  public final static cairo_status_t CAIRO_STATUS_NO_MEMORY = new cairo_status_t("CAIRO_STATUS_NO_MEMORY");
  public final static cairo_status_t CAIRO_STATUS_INVALID_RESTORE = new cairo_status_t("CAIRO_STATUS_INVALID_RESTORE");
  public final static cairo_status_t CAIRO_STATUS_INVALID_POP_GROUP = new cairo_status_t("CAIRO_STATUS_INVALID_POP_GROUP");
  public final static cairo_status_t CAIRO_STATUS_NO_CURRENT_POINT = new cairo_status_t("CAIRO_STATUS_NO_CURRENT_POINT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_MATRIX = new cairo_status_t("CAIRO_STATUS_INVALID_MATRIX");
  public final static cairo_status_t CAIRO_STATUS_INVALID_STATUS = new cairo_status_t("CAIRO_STATUS_INVALID_STATUS");
  public final static cairo_status_t CAIRO_STATUS_NULL_POINTER = new cairo_status_t("CAIRO_STATUS_NULL_POINTER");
  public final static cairo_status_t CAIRO_STATUS_INVALID_STRING = new cairo_status_t("CAIRO_STATUS_INVALID_STRING");
  public final static cairo_status_t CAIRO_STATUS_INVALID_PATH_DATA = new cairo_status_t("CAIRO_STATUS_INVALID_PATH_DATA");
  public final static cairo_status_t CAIRO_STATUS_READ_ERROR = new cairo_status_t("CAIRO_STATUS_READ_ERROR");
  public final static cairo_status_t CAIRO_STATUS_WRITE_ERROR = new cairo_status_t("CAIRO_STATUS_WRITE_ERROR");
  public final static cairo_status_t CAIRO_STATUS_SURFACE_FINISHED = new cairo_status_t("CAIRO_STATUS_SURFACE_FINISHED");
  public final static cairo_status_t CAIRO_STATUS_SURFACE_TYPE_MISMATCH = new cairo_status_t("CAIRO_STATUS_SURFACE_TYPE_MISMATCH");
  public final static cairo_status_t CAIRO_STATUS_PATTERN_TYPE_MISMATCH = new cairo_status_t("CAIRO_STATUS_PATTERN_TYPE_MISMATCH");
  public final static cairo_status_t CAIRO_STATUS_INVALID_CONTENT = new cairo_status_t("CAIRO_STATUS_INVALID_CONTENT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_FORMAT = new cairo_status_t("CAIRO_STATUS_INVALID_FORMAT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_VISUAL = new cairo_status_t("CAIRO_STATUS_INVALID_VISUAL");
  public final static cairo_status_t CAIRO_STATUS_FILE_NOT_FOUND = new cairo_status_t("CAIRO_STATUS_FILE_NOT_FOUND");
  public final static cairo_status_t CAIRO_STATUS_INVALID_DASH = new cairo_status_t("CAIRO_STATUS_INVALID_DASH");
  public final static cairo_status_t CAIRO_STATUS_INVALID_DSC_COMMENT = new cairo_status_t("CAIRO_STATUS_INVALID_DSC_COMMENT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_INDEX = new cairo_status_t("CAIRO_STATUS_INVALID_INDEX");
  public final static cairo_status_t CAIRO_STATUS_CLIP_NOT_REPRESENTABLE = new cairo_status_t("CAIRO_STATUS_CLIP_NOT_REPRESENTABLE");
  public final static cairo_status_t CAIRO_STATUS_TEMP_FILE_ERROR = new cairo_status_t("CAIRO_STATUS_TEMP_FILE_ERROR");
  public final static cairo_status_t CAIRO_STATUS_INVALID_STRIDE = new cairo_status_t("CAIRO_STATUS_INVALID_STRIDE");
  public final static cairo_status_t CAIRO_STATUS_FONT_TYPE_MISMATCH = new cairo_status_t("CAIRO_STATUS_FONT_TYPE_MISMATCH");
  public final static cairo_status_t CAIRO_STATUS_USER_FONT_IMMUTABLE = new cairo_status_t("CAIRO_STATUS_USER_FONT_IMMUTABLE");
  public final static cairo_status_t CAIRO_STATUS_USER_FONT_ERROR = new cairo_status_t("CAIRO_STATUS_USER_FONT_ERROR");
  public final static cairo_status_t CAIRO_STATUS_NEGATIVE_COUNT = new cairo_status_t("CAIRO_STATUS_NEGATIVE_COUNT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_CLUSTERS = new cairo_status_t("CAIRO_STATUS_INVALID_CLUSTERS");
  public final static cairo_status_t CAIRO_STATUS_INVALID_SLANT = new cairo_status_t("CAIRO_STATUS_INVALID_SLANT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_WEIGHT = new cairo_status_t("CAIRO_STATUS_INVALID_WEIGHT");
  public final static cairo_status_t CAIRO_STATUS_INVALID_SIZE = new cairo_status_t("CAIRO_STATUS_INVALID_SIZE");
  public final static cairo_status_t CAIRO_STATUS_USER_FONT_NOT_IMPLEMENTED = new cairo_status_t("CAIRO_STATUS_USER_FONT_NOT_IMPLEMENTED");
  public final static cairo_status_t CAIRO_STATUS_DEVICE_TYPE_MISMATCH = new cairo_status_t("CAIRO_STATUS_DEVICE_TYPE_MISMATCH");
  public final static cairo_status_t CAIRO_STATUS_DEVICE_ERROR = new cairo_status_t("CAIRO_STATUS_DEVICE_ERROR");
  public final static cairo_status_t CAIRO_STATUS_INVALID_MESH_CONSTRUCTION = new cairo_status_t("CAIRO_STATUS_INVALID_MESH_CONSTRUCTION");
  public final static cairo_status_t CAIRO_STATUS_DEVICE_FINISHED = new cairo_status_t("CAIRO_STATUS_DEVICE_FINISHED");
  public final static cairo_status_t CAIRO_STATUS_JBIG2_GLOBAL_MISSING = new cairo_status_t("CAIRO_STATUS_JBIG2_GLOBAL_MISSING");
  public final static cairo_status_t CAIRO_STATUS_LAST_STATUS = new cairo_status_t("CAIRO_STATUS_LAST_STATUS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cairo_status_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cairo_status_t.class + " with value " + swigValue);
  }

  private cairo_status_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cairo_status_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cairo_status_t(String swigName, cairo_status_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cairo_status_t[] swigValues = { CAIRO_STATUS_SUCCESS, CAIRO_STATUS_NO_MEMORY, CAIRO_STATUS_INVALID_RESTORE, CAIRO_STATUS_INVALID_POP_GROUP, CAIRO_STATUS_NO_CURRENT_POINT, CAIRO_STATUS_INVALID_MATRIX, CAIRO_STATUS_INVALID_STATUS, CAIRO_STATUS_NULL_POINTER, CAIRO_STATUS_INVALID_STRING, CAIRO_STATUS_INVALID_PATH_DATA, CAIRO_STATUS_READ_ERROR, CAIRO_STATUS_WRITE_ERROR, CAIRO_STATUS_SURFACE_FINISHED, CAIRO_STATUS_SURFACE_TYPE_MISMATCH, CAIRO_STATUS_PATTERN_TYPE_MISMATCH, CAIRO_STATUS_INVALID_CONTENT, CAIRO_STATUS_INVALID_FORMAT, CAIRO_STATUS_INVALID_VISUAL, CAIRO_STATUS_FILE_NOT_FOUND, CAIRO_STATUS_INVALID_DASH, CAIRO_STATUS_INVALID_DSC_COMMENT, CAIRO_STATUS_INVALID_INDEX, CAIRO_STATUS_CLIP_NOT_REPRESENTABLE, CAIRO_STATUS_TEMP_FILE_ERROR, CAIRO_STATUS_INVALID_STRIDE, CAIRO_STATUS_FONT_TYPE_MISMATCH, CAIRO_STATUS_USER_FONT_IMMUTABLE, CAIRO_STATUS_USER_FONT_ERROR, CAIRO_STATUS_NEGATIVE_COUNT, CAIRO_STATUS_INVALID_CLUSTERS, CAIRO_STATUS_INVALID_SLANT, CAIRO_STATUS_INVALID_WEIGHT, CAIRO_STATUS_INVALID_SIZE, CAIRO_STATUS_USER_FONT_NOT_IMPLEMENTED, CAIRO_STATUS_DEVICE_TYPE_MISMATCH, CAIRO_STATUS_DEVICE_ERROR, CAIRO_STATUS_INVALID_MESH_CONSTRUCTION, CAIRO_STATUS_DEVICE_FINISHED, CAIRO_STATUS_JBIG2_GLOBAL_MISSING, CAIRO_STATUS_LAST_STATUS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

