/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class cairo_font_extents_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cairo_font_extents_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cairo_font_extents_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cairoJNI.delete_cairo_font_extents_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAscent(double value) {
    cairoJNI.cairo_font_extents_t_ascent_set(swigCPtr, this, value);
  }

  public double getAscent() {
    return cairoJNI.cairo_font_extents_t_ascent_get(swigCPtr, this);
  }

  public void setDescent(double value) {
    cairoJNI.cairo_font_extents_t_descent_set(swigCPtr, this, value);
  }

  public double getDescent() {
    return cairoJNI.cairo_font_extents_t_descent_get(swigCPtr, this);
  }

  public void setHeight(double value) {
    cairoJNI.cairo_font_extents_t_height_set(swigCPtr, this, value);
  }

  public double getHeight() {
    return cairoJNI.cairo_font_extents_t_height_get(swigCPtr, this);
  }

  public void setMax_x_advance(double value) {
    cairoJNI.cairo_font_extents_t_max_x_advance_set(swigCPtr, this, value);
  }

  public double getMax_x_advance() {
    return cairoJNI.cairo_font_extents_t_max_x_advance_get(swigCPtr, this);
  }

  public void setMax_y_advance(double value) {
    cairoJNI.cairo_font_extents_t_max_y_advance_set(swigCPtr, this, value);
  }

  public double getMax_y_advance() {
    return cairoJNI.cairo_font_extents_t_max_y_advance_get(swigCPtr, this);
  }

  public cairo_font_extents_t() {
    this(cairoJNI.new_cairo_font_extents_t(), true);
  }

}
