/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class cairo_text_cluster_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cairo_text_cluster_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cairo_text_cluster_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete_cairo_text_cluster_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_bytes(int value) {
    pangoJNI.cairo_text_cluster_t_num_bytes_set(swigCPtr, this, value);
  }

  public int getNum_bytes() {
    return pangoJNI.cairo_text_cluster_t_num_bytes_get(swigCPtr, this);
  }

  public void setNum_glyphs(int value) {
    pangoJNI.cairo_text_cluster_t_num_glyphs_set(swigCPtr, this, value);
  }

  public int getNum_glyphs() {
    return pangoJNI.cairo_text_cluster_t_num_glyphs_get(swigCPtr, this);
  }

  public cairo_text_cluster_t() {
    this(pangoJNI.new_cairo_text_cluster_t(), true);
  }

}
