/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GConnectFlags {
  public final static GConnectFlags G_CONNECT_AFTER = new GConnectFlags("G_CONNECT_AFTER", pangoJNI.G_CONNECT_AFTER_get());
  public final static GConnectFlags G_CONNECT_SWAPPED = new GConnectFlags("G_CONNECT_SWAPPED", pangoJNI.G_CONNECT_SWAPPED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GConnectFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GConnectFlags.class + " with value " + swigValue);
  }

  private GConnectFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GConnectFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GConnectFlags(String swigName, GConnectFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GConnectFlags[] swigValues = { G_CONNECT_AFTER, G_CONNECT_SWAPPED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

