/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GDateDMY {
  public final static GDateDMY G_DATE_DAY = new GDateDMY("G_DATE_DAY", pangoJNI.G_DATE_DAY_get());
  public final static GDateDMY G_DATE_MONTH = new GDateDMY("G_DATE_MONTH", pangoJNI.G_DATE_MONTH_get());
  public final static GDateDMY G_DATE_YEAR = new GDateDMY("G_DATE_YEAR", pangoJNI.G_DATE_YEAR_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDateDMY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDateDMY.class + " with value " + swigValue);
  }

  private GDateDMY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDateDMY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GDateDMY(String swigName, GDateDMY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GDateDMY[] swigValues = { G_DATE_DAY, G_DATE_MONTH, G_DATE_YEAR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

