/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GErrorType {
  public final static GErrorType G_ERR_UNKNOWN = new GErrorType("G_ERR_UNKNOWN");
  public final static GErrorType G_ERR_UNEXP_EOF = new GErrorType("G_ERR_UNEXP_EOF");
  public final static GErrorType G_ERR_UNEXP_EOF_IN_STRING = new GErrorType("G_ERR_UNEXP_EOF_IN_STRING");
  public final static GErrorType G_ERR_UNEXP_EOF_IN_COMMENT = new GErrorType("G_ERR_UNEXP_EOF_IN_COMMENT");
  public final static GErrorType G_ERR_NON_DIGIT_IN_CONST = new GErrorType("G_ERR_NON_DIGIT_IN_CONST");
  public final static GErrorType G_ERR_DIGIT_RADIX = new GErrorType("G_ERR_DIGIT_RADIX");
  public final static GErrorType G_ERR_FLOAT_RADIX = new GErrorType("G_ERR_FLOAT_RADIX");
  public final static GErrorType G_ERR_FLOAT_MALFORMED = new GErrorType("G_ERR_FLOAT_MALFORMED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GErrorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GErrorType.class + " with value " + swigValue);
  }

  private GErrorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GErrorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GErrorType(String swigName, GErrorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GErrorType[] swigValues = { G_ERR_UNKNOWN, G_ERR_UNEXP_EOF, G_ERR_UNEXP_EOF_IN_STRING, G_ERR_UNEXP_EOF_IN_COMMENT, G_ERR_NON_DIGIT_IN_CONST, G_ERR_DIGIT_RADIX, G_ERR_FLOAT_RADIX, G_ERR_FLOAT_MALFORMED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

