/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GIOStatus {
  public final static GIOStatus G_IO_STATUS_ERROR = new GIOStatus("G_IO_STATUS_ERROR");
  public final static GIOStatus G_IO_STATUS_NORMAL = new GIOStatus("G_IO_STATUS_NORMAL");
  public final static GIOStatus G_IO_STATUS_EOF = new GIOStatus("G_IO_STATUS_EOF");
  public final static GIOStatus G_IO_STATUS_AGAIN = new GIOStatus("G_IO_STATUS_AGAIN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GIOStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GIOStatus.class + " with value " + swigValue);
  }

  private GIOStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GIOStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GIOStatus(String swigName, GIOStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GIOStatus[] swigValues = { G_IO_STATUS_ERROR, G_IO_STATUS_NORMAL, G_IO_STATUS_EOF, G_IO_STATUS_AGAIN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

