/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GKeyFileError {
  public final static GKeyFileError G_KEY_FILE_ERROR_UNKNOWN_ENCODING = new GKeyFileError("G_KEY_FILE_ERROR_UNKNOWN_ENCODING");
  public final static GKeyFileError G_KEY_FILE_ERROR_PARSE = new GKeyFileError("G_KEY_FILE_ERROR_PARSE");
  public final static GKeyFileError G_KEY_FILE_ERROR_NOT_FOUND = new GKeyFileError("G_KEY_FILE_ERROR_NOT_FOUND");
  public final static GKeyFileError G_KEY_FILE_ERROR_KEY_NOT_FOUND = new GKeyFileError("G_KEY_FILE_ERROR_KEY_NOT_FOUND");
  public final static GKeyFileError G_KEY_FILE_ERROR_GROUP_NOT_FOUND = new GKeyFileError("G_KEY_FILE_ERROR_GROUP_NOT_FOUND");
  public final static GKeyFileError G_KEY_FILE_ERROR_INVALID_VALUE = new GKeyFileError("G_KEY_FILE_ERROR_INVALID_VALUE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GKeyFileError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GKeyFileError.class + " with value " + swigValue);
  }

  private GKeyFileError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GKeyFileError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GKeyFileError(String swigName, GKeyFileError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GKeyFileError[] swigValues = { G_KEY_FILE_ERROR_UNKNOWN_ENCODING, G_KEY_FILE_ERROR_PARSE, G_KEY_FILE_ERROR_NOT_FOUND, G_KEY_FILE_ERROR_KEY_NOT_FOUND, G_KEY_FILE_ERROR_GROUP_NOT_FOUND, G_KEY_FILE_ERROR_INVALID_VALUE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

