/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GNormalizeMode {
  public final static GNormalizeMode G_NORMALIZE_DEFAULT = new GNormalizeMode("G_NORMALIZE_DEFAULT");
  public final static GNormalizeMode G_NORMALIZE_NFD = new GNormalizeMode("G_NORMALIZE_NFD", pangoJNI.G_NORMALIZE_NFD_get());
  public final static GNormalizeMode G_NORMALIZE_DEFAULT_COMPOSE = new GNormalizeMode("G_NORMALIZE_DEFAULT_COMPOSE");
  public final static GNormalizeMode G_NORMALIZE_NFC = new GNormalizeMode("G_NORMALIZE_NFC", pangoJNI.G_NORMALIZE_NFC_get());
  public final static GNormalizeMode G_NORMALIZE_ALL = new GNormalizeMode("G_NORMALIZE_ALL");
  public final static GNormalizeMode G_NORMALIZE_NFKD = new GNormalizeMode("G_NORMALIZE_NFKD", pangoJNI.G_NORMALIZE_NFKD_get());
  public final static GNormalizeMode G_NORMALIZE_ALL_COMPOSE = new GNormalizeMode("G_NORMALIZE_ALL_COMPOSE");
  public final static GNormalizeMode G_NORMALIZE_NFKC = new GNormalizeMode("G_NORMALIZE_NFKC", pangoJNI.G_NORMALIZE_NFKC_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GNormalizeMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GNormalizeMode.class + " with value " + swigValue);
  }

  private GNormalizeMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GNormalizeMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GNormalizeMode(String swigName, GNormalizeMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GNormalizeMode[] swigValues = { G_NORMALIZE_DEFAULT, G_NORMALIZE_NFD, G_NORMALIZE_DEFAULT_COMPOSE, G_NORMALIZE_NFC, G_NORMALIZE_ALL, G_NORMALIZE_NFKD, G_NORMALIZE_ALL_COMPOSE, G_NORMALIZE_NFKC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

