/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GOnceStatus {
  public final static GOnceStatus G_ONCE_STATUS_NOTCALLED = new GOnceStatus("G_ONCE_STATUS_NOTCALLED");
  public final static GOnceStatus G_ONCE_STATUS_PROGRESS = new GOnceStatus("G_ONCE_STATUS_PROGRESS");
  public final static GOnceStatus G_ONCE_STATUS_READY = new GOnceStatus("G_ONCE_STATUS_READY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GOnceStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GOnceStatus.class + " with value " + swigValue);
  }

  private GOnceStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GOnceStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GOnceStatus(String swigName, GOnceStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GOnceStatus[] swigValues = { G_ONCE_STATUS_NOTCALLED, G_ONCE_STATUS_PROGRESS, G_ONCE_STATUS_READY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

