/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GOptionError {
  public final static GOptionError G_OPTION_ERROR_UNKNOWN_OPTION = new GOptionError("G_OPTION_ERROR_UNKNOWN_OPTION");
  public final static GOptionError G_OPTION_ERROR_BAD_VALUE = new GOptionError("G_OPTION_ERROR_BAD_VALUE");
  public final static GOptionError G_OPTION_ERROR_FAILED = new GOptionError("G_OPTION_ERROR_FAILED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GOptionError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GOptionError.class + " with value " + swigValue);
  }

  private GOptionError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GOptionError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GOptionError(String swigName, GOptionError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GOptionError[] swigValues = { G_OPTION_ERROR_UNKNOWN_OPTION, G_OPTION_ERROR_BAD_VALUE, G_OPTION_ERROR_FAILED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

