/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GSeekType {
  public final static GSeekType G_SEEK_CUR = new GSeekType("G_SEEK_CUR");
  public final static GSeekType G_SEEK_SET = new GSeekType("G_SEEK_SET");
  public final static GSeekType G_SEEK_END = new GSeekType("G_SEEK_END");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GSeekType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GSeekType.class + " with value " + swigValue);
  }

  private GSeekType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GSeekType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GSeekType(String swigName, GSeekType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GSeekType[] swigValues = { G_SEEK_CUR, G_SEEK_SET, G_SEEK_END };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

