/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GSignalMatchType {
  public final static GSignalMatchType G_SIGNAL_MATCH_ID = new GSignalMatchType("G_SIGNAL_MATCH_ID", pangoJNI.G_SIGNAL_MATCH_ID_get());
  public final static GSignalMatchType G_SIGNAL_MATCH_DETAIL = new GSignalMatchType("G_SIGNAL_MATCH_DETAIL", pangoJNI.G_SIGNAL_MATCH_DETAIL_get());
  public final static GSignalMatchType G_SIGNAL_MATCH_CLOSURE = new GSignalMatchType("G_SIGNAL_MATCH_CLOSURE", pangoJNI.G_SIGNAL_MATCH_CLOSURE_get());
  public final static GSignalMatchType G_SIGNAL_MATCH_FUNC = new GSignalMatchType("G_SIGNAL_MATCH_FUNC", pangoJNI.G_SIGNAL_MATCH_FUNC_get());
  public final static GSignalMatchType G_SIGNAL_MATCH_DATA = new GSignalMatchType("G_SIGNAL_MATCH_DATA", pangoJNI.G_SIGNAL_MATCH_DATA_get());
  public final static GSignalMatchType G_SIGNAL_MATCH_UNBLOCKED = new GSignalMatchType("G_SIGNAL_MATCH_UNBLOCKED", pangoJNI.G_SIGNAL_MATCH_UNBLOCKED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GSignalMatchType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GSignalMatchType.class + " with value " + swigValue);
  }

  private GSignalMatchType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GSignalMatchType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GSignalMatchType(String swigName, GSignalMatchType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GSignalMatchType[] swigValues = { G_SIGNAL_MATCH_ID, G_SIGNAL_MATCH_DETAIL, G_SIGNAL_MATCH_CLOSURE, G_SIGNAL_MATCH_FUNC, G_SIGNAL_MATCH_DATA, G_SIGNAL_MATCH_UNBLOCKED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

