/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GSliceConfig {
  public final static GSliceConfig G_SLICE_CONFIG_ALWAYS_MALLOC = new GSliceConfig("G_SLICE_CONFIG_ALWAYS_MALLOC", pangoJNI.G_SLICE_CONFIG_ALWAYS_MALLOC_get());
  public final static GSliceConfig G_SLICE_CONFIG_BYPASS_MAGAZINES = new GSliceConfig("G_SLICE_CONFIG_BYPASS_MAGAZINES");
  public final static GSliceConfig G_SLICE_CONFIG_WORKING_SET_MSECS = new GSliceConfig("G_SLICE_CONFIG_WORKING_SET_MSECS");
  public final static GSliceConfig G_SLICE_CONFIG_COLOR_INCREMENT = new GSliceConfig("G_SLICE_CONFIG_COLOR_INCREMENT");
  public final static GSliceConfig G_SLICE_CONFIG_CHUNK_SIZES = new GSliceConfig("G_SLICE_CONFIG_CHUNK_SIZES");
  public final static GSliceConfig G_SLICE_CONFIG_CONTENTION_COUNTER = new GSliceConfig("G_SLICE_CONFIG_CONTENTION_COUNTER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GSliceConfig swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GSliceConfig.class + " with value " + swigValue);
  }

  private GSliceConfig(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GSliceConfig(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GSliceConfig(String swigName, GSliceConfig swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GSliceConfig[] swigValues = { G_SLICE_CONFIG_ALWAYS_MALLOC, G_SLICE_CONFIG_BYPASS_MAGAZINES, G_SLICE_CONFIG_WORKING_SET_MSECS, G_SLICE_CONFIG_COLOR_INCREMENT, G_SLICE_CONFIG_CHUNK_SIZES, G_SLICE_CONFIG_CONTENTION_COUNTER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

