/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class GStaticMutex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GStaticMutex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GStaticMutex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete_GStaticMutex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutex(_GMutex value) {
    pangoJNI.GStaticMutex_mutex_set(swigCPtr, this, _GMutex.getCPtr(value), value);
  }

  public _GMutex getMutex() {
    long cPtr = pangoJNI.GStaticMutex_mutex_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GMutex(cPtr, false);
  }

  public GStaticMutex() {
    this(pangoJNI.new_GStaticMutex(), true);
  }

}
