/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GTestTrapFlags {
  public final static GTestTrapFlags G_TEST_TRAP_SILENCE_STDOUT = new GTestTrapFlags("G_TEST_TRAP_SILENCE_STDOUT", pangoJNI.G_TEST_TRAP_SILENCE_STDOUT_get());
  public final static GTestTrapFlags G_TEST_TRAP_SILENCE_STDERR = new GTestTrapFlags("G_TEST_TRAP_SILENCE_STDERR", pangoJNI.G_TEST_TRAP_SILENCE_STDERR_get());
  public final static GTestTrapFlags G_TEST_TRAP_INHERIT_STDIN = new GTestTrapFlags("G_TEST_TRAP_INHERIT_STDIN", pangoJNI.G_TEST_TRAP_INHERIT_STDIN_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GTestTrapFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GTestTrapFlags.class + " with value " + swigValue);
  }

  private GTestTrapFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GTestTrapFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GTestTrapFlags(String swigName, GTestTrapFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GTestTrapFlags[] swigValues = { G_TEST_TRAP_SILENCE_STDOUT, G_TEST_TRAP_SILENCE_STDERR, G_TEST_TRAP_INHERIT_STDIN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

