/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class GTestConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GTestConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTestConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete_GTestConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTest_initialized(int value) {
    pangoJNI.GTestConfig_test_initialized_set(swigCPtr, this, value);
  }

  public int getTest_initialized() {
    return pangoJNI.GTestConfig_test_initialized_get(swigCPtr, this);
  }

  public void setTest_quick(int value) {
    pangoJNI.GTestConfig_test_quick_set(swigCPtr, this, value);
  }

  public int getTest_quick() {
    return pangoJNI.GTestConfig_test_quick_get(swigCPtr, this);
  }

  public void setTest_perf(int value) {
    pangoJNI.GTestConfig_test_perf_set(swigCPtr, this, value);
  }

  public int getTest_perf() {
    return pangoJNI.GTestConfig_test_perf_get(swigCPtr, this);
  }

  public void setTest_verbose(int value) {
    pangoJNI.GTestConfig_test_verbose_set(swigCPtr, this, value);
  }

  public int getTest_verbose() {
    return pangoJNI.GTestConfig_test_verbose_get(swigCPtr, this);
  }

  public void setTest_quiet(int value) {
    pangoJNI.GTestConfig_test_quiet_set(swigCPtr, this, value);
  }

  public int getTest_quiet() {
    return pangoJNI.GTestConfig_test_quiet_get(swigCPtr, this);
  }

  public void setTest_undefined(int value) {
    pangoJNI.GTestConfig_test_undefined_set(swigCPtr, this, value);
  }

  public int getTest_undefined() {
    return pangoJNI.GTestConfig_test_undefined_get(swigCPtr, this);
  }

  public GTestConfig() {
    this(pangoJNI.new_GTestConfig(), true);
  }

}
