/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GTimeType {
  public final static GTimeType G_TIME_TYPE_STANDARD = new GTimeType("G_TIME_TYPE_STANDARD");
  public final static GTimeType G_TIME_TYPE_DAYLIGHT = new GTimeType("G_TIME_TYPE_DAYLIGHT");
  public final static GTimeType G_TIME_TYPE_UNIVERSAL = new GTimeType("G_TIME_TYPE_UNIVERSAL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GTimeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GTimeType.class + " with value " + swigValue);
  }

  private GTimeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GTimeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GTimeType(String swigName, GTimeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GTimeType[] swigValues = { G_TIME_TYPE_STANDARD, G_TIME_TYPE_DAYLIGHT, G_TIME_TYPE_UNIVERSAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

