/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GTraverseType {
  public final static GTraverseType G_IN_ORDER = new GTraverseType("G_IN_ORDER");
  public final static GTraverseType G_PRE_ORDER = new GTraverseType("G_PRE_ORDER");
  public final static GTraverseType G_POST_ORDER = new GTraverseType("G_POST_ORDER");
  public final static GTraverseType G_LEVEL_ORDER = new GTraverseType("G_LEVEL_ORDER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GTraverseType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GTraverseType.class + " with value " + swigValue);
  }

  private GTraverseType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GTraverseType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GTraverseType(String swigName, GTraverseType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GTraverseType[] swigValues = { G_IN_ORDER, G_PRE_ORDER, G_POST_ORDER, G_LEVEL_ORDER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

