/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GTypeFundamentalFlags {
  public final static GTypeFundamentalFlags G_TYPE_FLAG_CLASSED = new GTypeFundamentalFlags("G_TYPE_FLAG_CLASSED", pangoJNI.G_TYPE_FLAG_CLASSED_get());
  public final static GTypeFundamentalFlags G_TYPE_FLAG_INSTANTIATABLE = new GTypeFundamentalFlags("G_TYPE_FLAG_INSTANTIATABLE", pangoJNI.G_TYPE_FLAG_INSTANTIATABLE_get());
  public final static GTypeFundamentalFlags G_TYPE_FLAG_DERIVABLE = new GTypeFundamentalFlags("G_TYPE_FLAG_DERIVABLE", pangoJNI.G_TYPE_FLAG_DERIVABLE_get());
  public final static GTypeFundamentalFlags G_TYPE_FLAG_DEEP_DERIVABLE = new GTypeFundamentalFlags("G_TYPE_FLAG_DEEP_DERIVABLE", pangoJNI.G_TYPE_FLAG_DEEP_DERIVABLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GTypeFundamentalFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GTypeFundamentalFlags.class + " with value " + swigValue);
  }

  private GTypeFundamentalFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GTypeFundamentalFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GTypeFundamentalFlags(String swigName, GTypeFundamentalFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GTypeFundamentalFlags[] swigValues = { G_TYPE_FLAG_CLASSED, G_TYPE_FLAG_INSTANTIATABLE, G_TYPE_FLAG_DERIVABLE, G_TYPE_FLAG_DEEP_DERIVABLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

