/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GUnicodeBreakType {
  public final static GUnicodeBreakType G_UNICODE_BREAK_MANDATORY = new GUnicodeBreakType("G_UNICODE_BREAK_MANDATORY");
  public final static GUnicodeBreakType G_UNICODE_BREAK_CARRIAGE_RETURN = new GUnicodeBreakType("G_UNICODE_BREAK_CARRIAGE_RETURN");
  public final static GUnicodeBreakType G_UNICODE_BREAK_LINE_FEED = new GUnicodeBreakType("G_UNICODE_BREAK_LINE_FEED");
  public final static GUnicodeBreakType G_UNICODE_BREAK_COMBINING_MARK = new GUnicodeBreakType("G_UNICODE_BREAK_COMBINING_MARK");
  public final static GUnicodeBreakType G_UNICODE_BREAK_SURROGATE = new GUnicodeBreakType("G_UNICODE_BREAK_SURROGATE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_ZERO_WIDTH_SPACE = new GUnicodeBreakType("G_UNICODE_BREAK_ZERO_WIDTH_SPACE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_INSEPARABLE = new GUnicodeBreakType("G_UNICODE_BREAK_INSEPARABLE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_NON_BREAKING_GLUE = new GUnicodeBreakType("G_UNICODE_BREAK_NON_BREAKING_GLUE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_CONTINGENT = new GUnicodeBreakType("G_UNICODE_BREAK_CONTINGENT");
  public final static GUnicodeBreakType G_UNICODE_BREAK_SPACE = new GUnicodeBreakType("G_UNICODE_BREAK_SPACE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_AFTER = new GUnicodeBreakType("G_UNICODE_BREAK_AFTER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_BEFORE = new GUnicodeBreakType("G_UNICODE_BREAK_BEFORE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_BEFORE_AND_AFTER = new GUnicodeBreakType("G_UNICODE_BREAK_BEFORE_AND_AFTER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HYPHEN = new GUnicodeBreakType("G_UNICODE_BREAK_HYPHEN");
  public final static GUnicodeBreakType G_UNICODE_BREAK_NON_STARTER = new GUnicodeBreakType("G_UNICODE_BREAK_NON_STARTER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_OPEN_PUNCTUATION = new GUnicodeBreakType("G_UNICODE_BREAK_OPEN_PUNCTUATION");
  public final static GUnicodeBreakType G_UNICODE_BREAK_CLOSE_PUNCTUATION = new GUnicodeBreakType("G_UNICODE_BREAK_CLOSE_PUNCTUATION");
  public final static GUnicodeBreakType G_UNICODE_BREAK_QUOTATION = new GUnicodeBreakType("G_UNICODE_BREAK_QUOTATION");
  public final static GUnicodeBreakType G_UNICODE_BREAK_EXCLAMATION = new GUnicodeBreakType("G_UNICODE_BREAK_EXCLAMATION");
  public final static GUnicodeBreakType G_UNICODE_BREAK_IDEOGRAPHIC = new GUnicodeBreakType("G_UNICODE_BREAK_IDEOGRAPHIC");
  public final static GUnicodeBreakType G_UNICODE_BREAK_NUMERIC = new GUnicodeBreakType("G_UNICODE_BREAK_NUMERIC");
  public final static GUnicodeBreakType G_UNICODE_BREAK_INFIX_SEPARATOR = new GUnicodeBreakType("G_UNICODE_BREAK_INFIX_SEPARATOR");
  public final static GUnicodeBreakType G_UNICODE_BREAK_SYMBOL = new GUnicodeBreakType("G_UNICODE_BREAK_SYMBOL");
  public final static GUnicodeBreakType G_UNICODE_BREAK_ALPHABETIC = new GUnicodeBreakType("G_UNICODE_BREAK_ALPHABETIC");
  public final static GUnicodeBreakType G_UNICODE_BREAK_PREFIX = new GUnicodeBreakType("G_UNICODE_BREAK_PREFIX");
  public final static GUnicodeBreakType G_UNICODE_BREAK_POSTFIX = new GUnicodeBreakType("G_UNICODE_BREAK_POSTFIX");
  public final static GUnicodeBreakType G_UNICODE_BREAK_COMPLEX_CONTEXT = new GUnicodeBreakType("G_UNICODE_BREAK_COMPLEX_CONTEXT");
  public final static GUnicodeBreakType G_UNICODE_BREAK_AMBIGUOUS = new GUnicodeBreakType("G_UNICODE_BREAK_AMBIGUOUS");
  public final static GUnicodeBreakType G_UNICODE_BREAK_UNKNOWN = new GUnicodeBreakType("G_UNICODE_BREAK_UNKNOWN");
  public final static GUnicodeBreakType G_UNICODE_BREAK_NEXT_LINE = new GUnicodeBreakType("G_UNICODE_BREAK_NEXT_LINE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_WORD_JOINER = new GUnicodeBreakType("G_UNICODE_BREAK_WORD_JOINER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HANGUL_L_JAMO = new GUnicodeBreakType("G_UNICODE_BREAK_HANGUL_L_JAMO");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HANGUL_V_JAMO = new GUnicodeBreakType("G_UNICODE_BREAK_HANGUL_V_JAMO");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HANGUL_T_JAMO = new GUnicodeBreakType("G_UNICODE_BREAK_HANGUL_T_JAMO");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HANGUL_LV_SYLLABLE = new GUnicodeBreakType("G_UNICODE_BREAK_HANGUL_LV_SYLLABLE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HANGUL_LVT_SYLLABLE = new GUnicodeBreakType("G_UNICODE_BREAK_HANGUL_LVT_SYLLABLE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_CLOSE_PARANTHESIS = new GUnicodeBreakType("G_UNICODE_BREAK_CLOSE_PARANTHESIS");
  public final static GUnicodeBreakType G_UNICODE_BREAK_CONDITIONAL_JAPANESE_STARTER = new GUnicodeBreakType("G_UNICODE_BREAK_CONDITIONAL_JAPANESE_STARTER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_HEBREW_LETTER = new GUnicodeBreakType("G_UNICODE_BREAK_HEBREW_LETTER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_REGIONAL_INDICATOR = new GUnicodeBreakType("G_UNICODE_BREAK_REGIONAL_INDICATOR");
  public final static GUnicodeBreakType G_UNICODE_BREAK_EMOJI_BASE = new GUnicodeBreakType("G_UNICODE_BREAK_EMOJI_BASE");
  public final static GUnicodeBreakType G_UNICODE_BREAK_EMOJI_MODIFIER = new GUnicodeBreakType("G_UNICODE_BREAK_EMOJI_MODIFIER");
  public final static GUnicodeBreakType G_UNICODE_BREAK_ZERO_WIDTH_JOINER = new GUnicodeBreakType("G_UNICODE_BREAK_ZERO_WIDTH_JOINER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GUnicodeBreakType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GUnicodeBreakType.class + " with value " + swigValue);
  }

  private GUnicodeBreakType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GUnicodeBreakType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GUnicodeBreakType(String swigName, GUnicodeBreakType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GUnicodeBreakType[] swigValues = { G_UNICODE_BREAK_MANDATORY, G_UNICODE_BREAK_CARRIAGE_RETURN, G_UNICODE_BREAK_LINE_FEED, G_UNICODE_BREAK_COMBINING_MARK, G_UNICODE_BREAK_SURROGATE, G_UNICODE_BREAK_ZERO_WIDTH_SPACE, G_UNICODE_BREAK_INSEPARABLE, G_UNICODE_BREAK_NON_BREAKING_GLUE, G_UNICODE_BREAK_CONTINGENT, G_UNICODE_BREAK_SPACE, G_UNICODE_BREAK_AFTER, G_UNICODE_BREAK_BEFORE, G_UNICODE_BREAK_BEFORE_AND_AFTER, G_UNICODE_BREAK_HYPHEN, G_UNICODE_BREAK_NON_STARTER, G_UNICODE_BREAK_OPEN_PUNCTUATION, G_UNICODE_BREAK_CLOSE_PUNCTUATION, G_UNICODE_BREAK_QUOTATION, G_UNICODE_BREAK_EXCLAMATION, G_UNICODE_BREAK_IDEOGRAPHIC, G_UNICODE_BREAK_NUMERIC, G_UNICODE_BREAK_INFIX_SEPARATOR, G_UNICODE_BREAK_SYMBOL, G_UNICODE_BREAK_ALPHABETIC, G_UNICODE_BREAK_PREFIX, G_UNICODE_BREAK_POSTFIX, G_UNICODE_BREAK_COMPLEX_CONTEXT, G_UNICODE_BREAK_AMBIGUOUS, G_UNICODE_BREAK_UNKNOWN, G_UNICODE_BREAK_NEXT_LINE, G_UNICODE_BREAK_WORD_JOINER, G_UNICODE_BREAK_HANGUL_L_JAMO, G_UNICODE_BREAK_HANGUL_V_JAMO, G_UNICODE_BREAK_HANGUL_T_JAMO, G_UNICODE_BREAK_HANGUL_LV_SYLLABLE, G_UNICODE_BREAK_HANGUL_LVT_SYLLABLE, G_UNICODE_BREAK_CLOSE_PARANTHESIS, G_UNICODE_BREAK_CONDITIONAL_JAPANESE_STARTER, G_UNICODE_BREAK_HEBREW_LETTER, G_UNICODE_BREAK_REGIONAL_INDICATOR, G_UNICODE_BREAK_EMOJI_BASE, G_UNICODE_BREAK_EMOJI_MODIFIER, G_UNICODE_BREAK_ZERO_WIDTH_JOINER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

