/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class GWeakRef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GWeakRef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GWeakRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pangoJNI.delete_GWeakRef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GWeakRef_priv getPriv() {
    long cPtr = pangoJNI.GWeakRef_priv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GWeakRef_priv(cPtr, false);
  }

  public GWeakRef() {
    this(pangoJNI.new_GWeakRef(), true);
  }

}
