/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class GWin32OSType {
  public final static GWin32OSType G_WIN32_OS_ANY = new GWin32OSType("G_WIN32_OS_ANY");
  public final static GWin32OSType G_WIN32_OS_WORKSTATION = new GWin32OSType("G_WIN32_OS_WORKSTATION");
  public final static GWin32OSType G_WIN32_OS_SERVER = new GWin32OSType("G_WIN32_OS_SERVER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GWin32OSType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GWin32OSType.class + " with value " + swigValue);
  }

  private GWin32OSType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GWin32OSType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GWin32OSType(String swigName, GWin32OSType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GWin32OSType[] swigValues = { G_WIN32_OS_ANY, G_WIN32_OS_WORKSTATION, G_WIN32_OS_SERVER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

