/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoEllipsizeMode {
  public final static PangoEllipsizeMode PANGO_ELLIPSIZE_NONE = new PangoEllipsizeMode("PANGO_ELLIPSIZE_NONE");
  public final static PangoEllipsizeMode PANGO_ELLIPSIZE_START = new PangoEllipsizeMode("PANGO_ELLIPSIZE_START");
  public final static PangoEllipsizeMode PANGO_ELLIPSIZE_MIDDLE = new PangoEllipsizeMode("PANGO_ELLIPSIZE_MIDDLE");
  public final static PangoEllipsizeMode PANGO_ELLIPSIZE_END = new PangoEllipsizeMode("PANGO_ELLIPSIZE_END");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoEllipsizeMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoEllipsizeMode.class + " with value " + swigValue);
  }

  private PangoEllipsizeMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoEllipsizeMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoEllipsizeMode(String swigName, PangoEllipsizeMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoEllipsizeMode[] swigValues = { PANGO_ELLIPSIZE_NONE, PANGO_ELLIPSIZE_START, PANGO_ELLIPSIZE_MIDDLE, PANGO_ELLIPSIZE_END };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

