/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoAttrType {
  public final static PangoAttrType PANGO_ATTR_INVALID = new PangoAttrType("PANGO_ATTR_INVALID");
  public final static PangoAttrType PANGO_ATTR_LANGUAGE = new PangoAttrType("PANGO_ATTR_LANGUAGE");
  public final static PangoAttrType PANGO_ATTR_FAMILY = new PangoAttrType("PANGO_ATTR_FAMILY");
  public final static PangoAttrType PANGO_ATTR_STYLE = new PangoAttrType("PANGO_ATTR_STYLE");
  public final static PangoAttrType PANGO_ATTR_WEIGHT = new PangoAttrType("PANGO_ATTR_WEIGHT");
  public final static PangoAttrType PANGO_ATTR_VARIANT = new PangoAttrType("PANGO_ATTR_VARIANT");
  public final static PangoAttrType PANGO_ATTR_STRETCH = new PangoAttrType("PANGO_ATTR_STRETCH");
  public final static PangoAttrType PANGO_ATTR_SIZE = new PangoAttrType("PANGO_ATTR_SIZE");
  public final static PangoAttrType PANGO_ATTR_FONT_DESC = new PangoAttrType("PANGO_ATTR_FONT_DESC");
  public final static PangoAttrType PANGO_ATTR_FOREGROUND = new PangoAttrType("PANGO_ATTR_FOREGROUND");
  public final static PangoAttrType PANGO_ATTR_BACKGROUND = new PangoAttrType("PANGO_ATTR_BACKGROUND");
  public final static PangoAttrType PANGO_ATTR_UNDERLINE = new PangoAttrType("PANGO_ATTR_UNDERLINE");
  public final static PangoAttrType PANGO_ATTR_STRIKETHROUGH = new PangoAttrType("PANGO_ATTR_STRIKETHROUGH");
  public final static PangoAttrType PANGO_ATTR_RISE = new PangoAttrType("PANGO_ATTR_RISE");
  public final static PangoAttrType PANGO_ATTR_SHAPE = new PangoAttrType("PANGO_ATTR_SHAPE");
  public final static PangoAttrType PANGO_ATTR_SCALE = new PangoAttrType("PANGO_ATTR_SCALE");
  public final static PangoAttrType PANGO_ATTR_FALLBACK = new PangoAttrType("PANGO_ATTR_FALLBACK");
  public final static PangoAttrType PANGO_ATTR_LETTER_SPACING = new PangoAttrType("PANGO_ATTR_LETTER_SPACING");
  public final static PangoAttrType PANGO_ATTR_UNDERLINE_COLOR = new PangoAttrType("PANGO_ATTR_UNDERLINE_COLOR");
  public final static PangoAttrType PANGO_ATTR_STRIKETHROUGH_COLOR = new PangoAttrType("PANGO_ATTR_STRIKETHROUGH_COLOR");
  public final static PangoAttrType PANGO_ATTR_ABSOLUTE_SIZE = new PangoAttrType("PANGO_ATTR_ABSOLUTE_SIZE");
  public final static PangoAttrType PANGO_ATTR_GRAVITY = new PangoAttrType("PANGO_ATTR_GRAVITY");
  public final static PangoAttrType PANGO_ATTR_GRAVITY_HINT = new PangoAttrType("PANGO_ATTR_GRAVITY_HINT");
  public final static PangoAttrType PANGO_ATTR_FONT_FEATURES = new PangoAttrType("PANGO_ATTR_FONT_FEATURES");
  public final static PangoAttrType PANGO_ATTR_FOREGROUND_ALPHA = new PangoAttrType("PANGO_ATTR_FOREGROUND_ALPHA");
  public final static PangoAttrType PANGO_ATTR_BACKGROUND_ALPHA = new PangoAttrType("PANGO_ATTR_BACKGROUND_ALPHA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoAttrType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoAttrType.class + " with value " + swigValue);
  }

  private PangoAttrType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoAttrType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoAttrType(String swigName, PangoAttrType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoAttrType[] swigValues = { PANGO_ATTR_INVALID, PANGO_ATTR_LANGUAGE, PANGO_ATTR_FAMILY, PANGO_ATTR_STYLE, PANGO_ATTR_WEIGHT, PANGO_ATTR_VARIANT, PANGO_ATTR_STRETCH, PANGO_ATTR_SIZE, PANGO_ATTR_FONT_DESC, PANGO_ATTR_FOREGROUND, PANGO_ATTR_BACKGROUND, PANGO_ATTR_UNDERLINE, PANGO_ATTR_STRIKETHROUGH, PANGO_ATTR_RISE, PANGO_ATTR_SHAPE, PANGO_ATTR_SCALE, PANGO_ATTR_FALLBACK, PANGO_ATTR_LETTER_SPACING, PANGO_ATTR_UNDERLINE_COLOR, PANGO_ATTR_STRIKETHROUGH_COLOR, PANGO_ATTR_ABSOLUTE_SIZE, PANGO_ATTR_GRAVITY, PANGO_ATTR_GRAVITY_HINT, PANGO_ATTR_FONT_FEATURES, PANGO_ATTR_FOREGROUND_ALPHA, PANGO_ATTR_BACKGROUND_ALPHA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

