/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoWeight {
  public final static PangoWeight PANGO_WEIGHT_THIN = new PangoWeight("PANGO_WEIGHT_THIN", pangoJNI.PANGO_WEIGHT_THIN_get());
  public final static PangoWeight PANGO_WEIGHT_ULTRALIGHT = new PangoWeight("PANGO_WEIGHT_ULTRALIGHT", pangoJNI.PANGO_WEIGHT_ULTRALIGHT_get());
  public final static PangoWeight PANGO_WEIGHT_LIGHT = new PangoWeight("PANGO_WEIGHT_LIGHT", pangoJNI.PANGO_WEIGHT_LIGHT_get());
  public final static PangoWeight PANGO_WEIGHT_SEMILIGHT = new PangoWeight("PANGO_WEIGHT_SEMILIGHT", pangoJNI.PANGO_WEIGHT_SEMILIGHT_get());
  public final static PangoWeight PANGO_WEIGHT_BOOK = new PangoWeight("PANGO_WEIGHT_BOOK", pangoJNI.PANGO_WEIGHT_BOOK_get());
  public final static PangoWeight PANGO_WEIGHT_NORMAL = new PangoWeight("PANGO_WEIGHT_NORMAL", pangoJNI.PANGO_WEIGHT_NORMAL_get());
  public final static PangoWeight PANGO_WEIGHT_MEDIUM = new PangoWeight("PANGO_WEIGHT_MEDIUM", pangoJNI.PANGO_WEIGHT_MEDIUM_get());
  public final static PangoWeight PANGO_WEIGHT_SEMIBOLD = new PangoWeight("PANGO_WEIGHT_SEMIBOLD", pangoJNI.PANGO_WEIGHT_SEMIBOLD_get());
  public final static PangoWeight PANGO_WEIGHT_BOLD = new PangoWeight("PANGO_WEIGHT_BOLD", pangoJNI.PANGO_WEIGHT_BOLD_get());
  public final static PangoWeight PANGO_WEIGHT_ULTRABOLD = new PangoWeight("PANGO_WEIGHT_ULTRABOLD", pangoJNI.PANGO_WEIGHT_ULTRABOLD_get());
  public final static PangoWeight PANGO_WEIGHT_HEAVY = new PangoWeight("PANGO_WEIGHT_HEAVY", pangoJNI.PANGO_WEIGHT_HEAVY_get());
  public final static PangoWeight PANGO_WEIGHT_ULTRAHEAVY = new PangoWeight("PANGO_WEIGHT_ULTRAHEAVY", pangoJNI.PANGO_WEIGHT_ULTRAHEAVY_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoWeight swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoWeight.class + " with value " + swigValue);
  }

  private PangoWeight(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoWeight(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoWeight(String swigName, PangoWeight swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoWeight[] swigValues = { PANGO_WEIGHT_THIN, PANGO_WEIGHT_ULTRALIGHT, PANGO_WEIGHT_LIGHT, PANGO_WEIGHT_SEMILIGHT, PANGO_WEIGHT_BOOK, PANGO_WEIGHT_NORMAL, PANGO_WEIGHT_MEDIUM, PANGO_WEIGHT_SEMIBOLD, PANGO_WEIGHT_BOLD, PANGO_WEIGHT_ULTRABOLD, PANGO_WEIGHT_HEAVY, PANGO_WEIGHT_ULTRAHEAVY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

