/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoTabAlign {
  public final static PangoTabAlign PANGO_TAB_LEFT = new PangoTabAlign("PANGO_TAB_LEFT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoTabAlign swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoTabAlign.class + " with value " + swigValue);
  }

  private PangoTabAlign(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoTabAlign(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoTabAlign(String swigName, PangoTabAlign swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoTabAlign[] swigValues = { PANGO_TAB_LEFT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

