/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoStyle {
  public final static PangoStyle PANGO_STYLE_NORMAL = new PangoStyle("PANGO_STYLE_NORMAL");
  public final static PangoStyle PANGO_STYLE_OBLIQUE = new PangoStyle("PANGO_STYLE_OBLIQUE");
  public final static PangoStyle PANGO_STYLE_ITALIC = new PangoStyle("PANGO_STYLE_ITALIC");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoStyle swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoStyle.class + " with value " + swigValue);
  }

  private PangoStyle(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoStyle(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoStyle(String swigName, PangoStyle swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoStyle[] swigValues = { PANGO_STYLE_NORMAL, PANGO_STYLE_OBLIQUE, PANGO_STYLE_ITALIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

