/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoStretch {
  public final static PangoStretch PANGO_STRETCH_ULTRA_CONDENSED = new PangoStretch("PANGO_STRETCH_ULTRA_CONDENSED");
  public final static PangoStretch PANGO_STRETCH_EXTRA_CONDENSED = new PangoStretch("PANGO_STRETCH_EXTRA_CONDENSED");
  public final static PangoStretch PANGO_STRETCH_CONDENSED = new PangoStretch("PANGO_STRETCH_CONDENSED");
  public final static PangoStretch PANGO_STRETCH_SEMI_CONDENSED = new PangoStretch("PANGO_STRETCH_SEMI_CONDENSED");
  public final static PangoStretch PANGO_STRETCH_NORMAL = new PangoStretch("PANGO_STRETCH_NORMAL");
  public final static PangoStretch PANGO_STRETCH_SEMI_EXPANDED = new PangoStretch("PANGO_STRETCH_SEMI_EXPANDED");
  public final static PangoStretch PANGO_STRETCH_EXPANDED = new PangoStretch("PANGO_STRETCH_EXPANDED");
  public final static PangoStretch PANGO_STRETCH_EXTRA_EXPANDED = new PangoStretch("PANGO_STRETCH_EXTRA_EXPANDED");
  public final static PangoStretch PANGO_STRETCH_ULTRA_EXPANDED = new PangoStretch("PANGO_STRETCH_ULTRA_EXPANDED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoStretch swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoStretch.class + " with value " + swigValue);
  }

  private PangoStretch(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoStretch(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoStretch(String swigName, PangoStretch swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoStretch[] swigValues = { PANGO_STRETCH_ULTRA_CONDENSED, PANGO_STRETCH_EXTRA_CONDENSED, PANGO_STRETCH_CONDENSED, PANGO_STRETCH_SEMI_CONDENSED, PANGO_STRETCH_NORMAL, PANGO_STRETCH_SEMI_EXPANDED, PANGO_STRETCH_EXPANDED, PANGO_STRETCH_EXTRA_EXPANDED, PANGO_STRETCH_ULTRA_EXPANDED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

