/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoVariant {
  public final static PangoVariant PANGO_VARIANT_NORMAL = new PangoVariant("PANGO_VARIANT_NORMAL");
  public final static PangoVariant PANGO_VARIANT_SMALL_CAPS = new PangoVariant("PANGO_VARIANT_SMALL_CAPS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoVariant swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoVariant.class + " with value " + swigValue);
  }

  private PangoVariant(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoVariant(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoVariant(String swigName, PangoVariant swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoVariant[] swigValues = { PANGO_VARIANT_NORMAL, PANGO_VARIANT_SMALL_CAPS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

