/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoBidiType {
  public final static PangoBidiType PANGO_BIDI_TYPE_L = new PangoBidiType("PANGO_BIDI_TYPE_L");
  public final static PangoBidiType PANGO_BIDI_TYPE_LRE = new PangoBidiType("PANGO_BIDI_TYPE_LRE");
  public final static PangoBidiType PANGO_BIDI_TYPE_LRO = new PangoBidiType("PANGO_BIDI_TYPE_LRO");
  public final static PangoBidiType PANGO_BIDI_TYPE_R = new PangoBidiType("PANGO_BIDI_TYPE_R");
  public final static PangoBidiType PANGO_BIDI_TYPE_AL = new PangoBidiType("PANGO_BIDI_TYPE_AL");
  public final static PangoBidiType PANGO_BIDI_TYPE_RLE = new PangoBidiType("PANGO_BIDI_TYPE_RLE");
  public final static PangoBidiType PANGO_BIDI_TYPE_RLO = new PangoBidiType("PANGO_BIDI_TYPE_RLO");
  public final static PangoBidiType PANGO_BIDI_TYPE_PDF = new PangoBidiType("PANGO_BIDI_TYPE_PDF");
  public final static PangoBidiType PANGO_BIDI_TYPE_EN = new PangoBidiType("PANGO_BIDI_TYPE_EN");
  public final static PangoBidiType PANGO_BIDI_TYPE_ES = new PangoBidiType("PANGO_BIDI_TYPE_ES");
  public final static PangoBidiType PANGO_BIDI_TYPE_ET = new PangoBidiType("PANGO_BIDI_TYPE_ET");
  public final static PangoBidiType PANGO_BIDI_TYPE_AN = new PangoBidiType("PANGO_BIDI_TYPE_AN");
  public final static PangoBidiType PANGO_BIDI_TYPE_CS = new PangoBidiType("PANGO_BIDI_TYPE_CS");
  public final static PangoBidiType PANGO_BIDI_TYPE_NSM = new PangoBidiType("PANGO_BIDI_TYPE_NSM");
  public final static PangoBidiType PANGO_BIDI_TYPE_BN = new PangoBidiType("PANGO_BIDI_TYPE_BN");
  public final static PangoBidiType PANGO_BIDI_TYPE_B = new PangoBidiType("PANGO_BIDI_TYPE_B");
  public final static PangoBidiType PANGO_BIDI_TYPE_S = new PangoBidiType("PANGO_BIDI_TYPE_S");
  public final static PangoBidiType PANGO_BIDI_TYPE_WS = new PangoBidiType("PANGO_BIDI_TYPE_WS");
  public final static PangoBidiType PANGO_BIDI_TYPE_ON = new PangoBidiType("PANGO_BIDI_TYPE_ON");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoBidiType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoBidiType.class + " with value " + swigValue);
  }

  private PangoBidiType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoBidiType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoBidiType(String swigName, PangoBidiType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoBidiType[] swigValues = { PANGO_BIDI_TYPE_L, PANGO_BIDI_TYPE_LRE, PANGO_BIDI_TYPE_LRO, PANGO_BIDI_TYPE_R, PANGO_BIDI_TYPE_AL, PANGO_BIDI_TYPE_RLE, PANGO_BIDI_TYPE_RLO, PANGO_BIDI_TYPE_PDF, PANGO_BIDI_TYPE_EN, PANGO_BIDI_TYPE_ES, PANGO_BIDI_TYPE_ET, PANGO_BIDI_TYPE_AN, PANGO_BIDI_TYPE_CS, PANGO_BIDI_TYPE_NSM, PANGO_BIDI_TYPE_BN, PANGO_BIDI_TYPE_B, PANGO_BIDI_TYPE_S, PANGO_BIDI_TYPE_WS, PANGO_BIDI_TYPE_ON };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

