/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoAlignment {
  public final static PangoAlignment PANGO_ALIGN_LEFT = new PangoAlignment("PANGO_ALIGN_LEFT");
  public final static PangoAlignment PANGO_ALIGN_CENTER = new PangoAlignment("PANGO_ALIGN_CENTER");
  public final static PangoAlignment PANGO_ALIGN_RIGHT = new PangoAlignment("PANGO_ALIGN_RIGHT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoAlignment swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoAlignment.class + " with value " + swigValue);
  }

  private PangoAlignment(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoAlignment(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoAlignment(String swigName, PangoAlignment swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoAlignment[] swigValues = { PANGO_ALIGN_LEFT, PANGO_ALIGN_CENTER, PANGO_ALIGN_RIGHT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

