/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoCoverageLevel {
  public final static PangoCoverageLevel PANGO_COVERAGE_NONE = new PangoCoverageLevel("PANGO_COVERAGE_NONE");
  public final static PangoCoverageLevel PANGO_COVERAGE_FALLBACK = new PangoCoverageLevel("PANGO_COVERAGE_FALLBACK");
  public final static PangoCoverageLevel PANGO_COVERAGE_APPROXIMATE = new PangoCoverageLevel("PANGO_COVERAGE_APPROXIMATE");
  public final static PangoCoverageLevel PANGO_COVERAGE_EXACT = new PangoCoverageLevel("PANGO_COVERAGE_EXACT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoCoverageLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoCoverageLevel.class + " with value " + swigValue);
  }

  private PangoCoverageLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoCoverageLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoCoverageLevel(String swigName, PangoCoverageLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoCoverageLevel[] swigValues = { PANGO_COVERAGE_NONE, PANGO_COVERAGE_FALLBACK, PANGO_COVERAGE_APPROXIMATE, PANGO_COVERAGE_EXACT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

