/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoFontMask {
  public final static PangoFontMask PANGO_FONT_MASK_FAMILY = new PangoFontMask("PANGO_FONT_MASK_FAMILY", pangoJNI.PANGO_FONT_MASK_FAMILY_get());
  public final static PangoFontMask PANGO_FONT_MASK_STYLE = new PangoFontMask("PANGO_FONT_MASK_STYLE", pangoJNI.PANGO_FONT_MASK_STYLE_get());
  public final static PangoFontMask PANGO_FONT_MASK_VARIANT = new PangoFontMask("PANGO_FONT_MASK_VARIANT", pangoJNI.PANGO_FONT_MASK_VARIANT_get());
  public final static PangoFontMask PANGO_FONT_MASK_WEIGHT = new PangoFontMask("PANGO_FONT_MASK_WEIGHT", pangoJNI.PANGO_FONT_MASK_WEIGHT_get());
  public final static PangoFontMask PANGO_FONT_MASK_STRETCH = new PangoFontMask("PANGO_FONT_MASK_STRETCH", pangoJNI.PANGO_FONT_MASK_STRETCH_get());
  public final static PangoFontMask PANGO_FONT_MASK_SIZE = new PangoFontMask("PANGO_FONT_MASK_SIZE", pangoJNI.PANGO_FONT_MASK_SIZE_get());
  public final static PangoFontMask PANGO_FONT_MASK_GRAVITY = new PangoFontMask("PANGO_FONT_MASK_GRAVITY", pangoJNI.PANGO_FONT_MASK_GRAVITY_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoFontMask swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoFontMask.class + " with value " + swigValue);
  }

  private PangoFontMask(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoFontMask(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoFontMask(String swigName, PangoFontMask swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoFontMask[] swigValues = { PANGO_FONT_MASK_FAMILY, PANGO_FONT_MASK_STYLE, PANGO_FONT_MASK_VARIANT, PANGO_FONT_MASK_WEIGHT, PANGO_FONT_MASK_STRETCH, PANGO_FONT_MASK_SIZE, PANGO_FONT_MASK_GRAVITY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

