/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class PangoWrapMode {
  public final static PangoWrapMode PANGO_WRAP_WORD = new PangoWrapMode("PANGO_WRAP_WORD");
  public final static PangoWrapMode PANGO_WRAP_CHAR = new PangoWrapMode("PANGO_WRAP_CHAR");
  public final static PangoWrapMode PANGO_WRAP_WORD_CHAR = new PangoWrapMode("PANGO_WRAP_WORD_CHAR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PangoWrapMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PangoWrapMode.class + " with value " + swigValue);
  }

  private PangoWrapMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PangoWrapMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PangoWrapMode(String swigName, PangoWrapMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PangoWrapMode[] swigValues = { PANGO_WRAP_WORD, PANGO_WRAP_CHAR, PANGO_WRAP_WORD_CHAR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

