/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public interface SDL2Constants {
  public final static long SDL_INIT_TIMER = SDL2JNI.SDL_INIT_TIMER_get();
  public final static long SDL_INIT_AUDIO = SDL2JNI.SDL_INIT_AUDIO_get();
  public final static long SDL_INIT_VIDEO = SDL2JNI.SDL_INIT_VIDEO_get();
  public final static long SDL_INIT_JOYSTICK = SDL2JNI.SDL_INIT_JOYSTICK_get();
  public final static long SDL_INIT_HAPTIC = SDL2JNI.SDL_INIT_HAPTIC_get();
  public final static long SDL_INIT_GAMECONTROLLER = SDL2JNI.SDL_INIT_GAMECONTROLLER_get();
  public final static long SDL_INIT_EVENTS = SDL2JNI.SDL_INIT_EVENTS_get();
  public final static long SDL_INIT_NOPARACHUTE = SDL2JNI.SDL_INIT_NOPARACHUTE_get();
  public final static long SDL_INIT_EVERYTHING = SDL2JNI.SDL_INIT_EVERYTHING_get();
  public final static long SDL_WINDOWPOS_UNDEFINED_MASK = SDL2JNI.SDL_WINDOWPOS_UNDEFINED_MASK_get();
  public final static long SDL_WINDOWPOS_UNDEFINED = SDL2JNI.SDL_WINDOWPOS_UNDEFINED_get();
  public final static long SDL_WINDOWPOS_CENTERED_MASK = SDL2JNI.SDL_WINDOWPOS_CENTERED_MASK_get();
  public final static long SDL_WINDOWPOS_CENTERED = SDL2JNI.SDL_WINDOWPOS_CENTERED_get();
  public final static int SDL_RELEASED = SDL2JNI.SDL_RELEASED_get();
  public final static int SDL_PRESSED = SDL2JNI.SDL_PRESSED_get();
  public final static int SDL_TEXTEDITINGEVENT_TEXT_SIZE = SDL2JNI.SDL_TEXTEDITINGEVENT_TEXT_SIZE_get();
  public final static int SDL_TEXTINPUTEVENT_TEXT_SIZE = SDL2JNI.SDL_TEXTINPUTEVENT_TEXT_SIZE_get();
  public final static int SDL_QUERY = SDL2JNI.SDL_QUERY_get();
  public final static int SDL_IGNORE = SDL2JNI.SDL_IGNORE_get();
  public final static int SDL_DISABLE = SDL2JNI.SDL_DISABLE_get();
  public final static int SDL_ENABLE = SDL2JNI.SDL_ENABLE_get();
  public final static int SDL_ALPHA_OPAQUE = SDL2JNI.SDL_ALPHA_OPAQUE_get();
  public final static int SDL_ALPHA_TRANSPARENT = SDL2JNI.SDL_ALPHA_TRANSPARENT_get();
  public final static int SDL_PIXELTYPE_UNKNOWN = SDL2JNI.SDL_PIXELTYPE_UNKNOWN_get();
  public final static int SDL_PIXELTYPE_INDEX1 = SDL2JNI.SDL_PIXELTYPE_INDEX1_get();
  public final static int SDL_PIXELTYPE_INDEX4 = SDL2JNI.SDL_PIXELTYPE_INDEX4_get();
  public final static int SDL_PIXELTYPE_INDEX8 = SDL2JNI.SDL_PIXELTYPE_INDEX8_get();
  public final static int SDL_PIXELTYPE_PACKED8 = SDL2JNI.SDL_PIXELTYPE_PACKED8_get();
  public final static int SDL_PIXELTYPE_PACKED16 = SDL2JNI.SDL_PIXELTYPE_PACKED16_get();
  public final static int SDL_PIXELTYPE_PACKED32 = SDL2JNI.SDL_PIXELTYPE_PACKED32_get();
  public final static int SDL_PIXELTYPE_ARRAYU8 = SDL2JNI.SDL_PIXELTYPE_ARRAYU8_get();
  public final static int SDL_PIXELTYPE_ARRAYU16 = SDL2JNI.SDL_PIXELTYPE_ARRAYU16_get();
  public final static int SDL_PIXELTYPE_ARRAYU32 = SDL2JNI.SDL_PIXELTYPE_ARRAYU32_get();
  public final static int SDL_PIXELTYPE_ARRAYF16 = SDL2JNI.SDL_PIXELTYPE_ARRAYF16_get();
  public final static int SDL_PIXELTYPE_ARRAYF32 = SDL2JNI.SDL_PIXELTYPE_ARRAYF32_get();

  public final static int SDL_BITMAPORDER_NONE = SDL2JNI.SDL_BITMAPORDER_NONE_get();
  public final static int SDL_BITMAPORDER_4321 = SDL2JNI.SDL_BITMAPORDER_4321_get();
  public final static int SDL_BITMAPORDER_1234 = SDL2JNI.SDL_BITMAPORDER_1234_get();

  public final static int SDL_PACKEDORDER_NONE = SDL2JNI.SDL_PACKEDORDER_NONE_get();
  public final static int SDL_PACKEDORDER_XRGB = SDL2JNI.SDL_PACKEDORDER_XRGB_get();
  public final static int SDL_PACKEDORDER_RGBX = SDL2JNI.SDL_PACKEDORDER_RGBX_get();
  public final static int SDL_PACKEDORDER_ARGB = SDL2JNI.SDL_PACKEDORDER_ARGB_get();
  public final static int SDL_PACKEDORDER_RGBA = SDL2JNI.SDL_PACKEDORDER_RGBA_get();
  public final static int SDL_PACKEDORDER_XBGR = SDL2JNI.SDL_PACKEDORDER_XBGR_get();
  public final static int SDL_PACKEDORDER_BGRX = SDL2JNI.SDL_PACKEDORDER_BGRX_get();
  public final static int SDL_PACKEDORDER_ABGR = SDL2JNI.SDL_PACKEDORDER_ABGR_get();
  public final static int SDL_PACKEDORDER_BGRA = SDL2JNI.SDL_PACKEDORDER_BGRA_get();

  public final static int SDL_ARRAYORDER_NONE = SDL2JNI.SDL_ARRAYORDER_NONE_get();
  public final static int SDL_ARRAYORDER_RGB = SDL2JNI.SDL_ARRAYORDER_RGB_get();
  public final static int SDL_ARRAYORDER_RGBA = SDL2JNI.SDL_ARRAYORDER_RGBA_get();
  public final static int SDL_ARRAYORDER_ARGB = SDL2JNI.SDL_ARRAYORDER_ARGB_get();
  public final static int SDL_ARRAYORDER_BGR = SDL2JNI.SDL_ARRAYORDER_BGR_get();
  public final static int SDL_ARRAYORDER_BGRA = SDL2JNI.SDL_ARRAYORDER_BGRA_get();
  public final static int SDL_ARRAYORDER_ABGR = SDL2JNI.SDL_ARRAYORDER_ABGR_get();

  public final static int SDL_PACKEDLAYOUT_NONE = SDL2JNI.SDL_PACKEDLAYOUT_NONE_get();
  public final static int SDL_PACKEDLAYOUT_332 = SDL2JNI.SDL_PACKEDLAYOUT_332_get();
  public final static int SDL_PACKEDLAYOUT_4444 = SDL2JNI.SDL_PACKEDLAYOUT_4444_get();
  public final static int SDL_PACKEDLAYOUT_1555 = SDL2JNI.SDL_PACKEDLAYOUT_1555_get();
  public final static int SDL_PACKEDLAYOUT_5551 = SDL2JNI.SDL_PACKEDLAYOUT_5551_get();
  public final static int SDL_PACKEDLAYOUT_565 = SDL2JNI.SDL_PACKEDLAYOUT_565_get();
  public final static int SDL_PACKEDLAYOUT_8888 = SDL2JNI.SDL_PACKEDLAYOUT_8888_get();
  public final static int SDL_PACKEDLAYOUT_2101010 = SDL2JNI.SDL_PACKEDLAYOUT_2101010_get();
  public final static int SDL_PACKEDLAYOUT_1010102 = SDL2JNI.SDL_PACKEDLAYOUT_1010102_get();

  public final static int SDL_PIXELFORMAT_UNKNOWN = SDL2JNI.SDL_PIXELFORMAT_UNKNOWN_get();
  public final static int SDL_PIXELFORMAT_INDEX1LSB = SDL2JNI.SDL_PIXELFORMAT_INDEX1LSB_get();
  public final static int SDL_PIXELFORMAT_INDEX1MSB = SDL2JNI.SDL_PIXELFORMAT_INDEX1MSB_get();
  public final static int SDL_PIXELFORMAT_INDEX4LSB = SDL2JNI.SDL_PIXELFORMAT_INDEX4LSB_get();
  public final static int SDL_PIXELFORMAT_INDEX4MSB = SDL2JNI.SDL_PIXELFORMAT_INDEX4MSB_get();
  public final static int SDL_PIXELFORMAT_INDEX8 = SDL2JNI.SDL_PIXELFORMAT_INDEX8_get();
  public final static int SDL_PIXELFORMAT_RGB332 = SDL2JNI.SDL_PIXELFORMAT_RGB332_get();
  public final static int SDL_PIXELFORMAT_RGB444 = SDL2JNI.SDL_PIXELFORMAT_RGB444_get();
  public final static int SDL_PIXELFORMAT_RGB555 = SDL2JNI.SDL_PIXELFORMAT_RGB555_get();
  public final static int SDL_PIXELFORMAT_BGR555 = SDL2JNI.SDL_PIXELFORMAT_BGR555_get();
  public final static int SDL_PIXELFORMAT_ARGB4444 = SDL2JNI.SDL_PIXELFORMAT_ARGB4444_get();
  public final static int SDL_PIXELFORMAT_RGBA4444 = SDL2JNI.SDL_PIXELFORMAT_RGBA4444_get();
  public final static int SDL_PIXELFORMAT_ABGR4444 = SDL2JNI.SDL_PIXELFORMAT_ABGR4444_get();
  public final static int SDL_PIXELFORMAT_BGRA4444 = SDL2JNI.SDL_PIXELFORMAT_BGRA4444_get();
  public final static int SDL_PIXELFORMAT_ARGB1555 = SDL2JNI.SDL_PIXELFORMAT_ARGB1555_get();
  public final static int SDL_PIXELFORMAT_RGBA5551 = SDL2JNI.SDL_PIXELFORMAT_RGBA5551_get();
  public final static int SDL_PIXELFORMAT_ABGR1555 = SDL2JNI.SDL_PIXELFORMAT_ABGR1555_get();
  public final static int SDL_PIXELFORMAT_BGRA5551 = SDL2JNI.SDL_PIXELFORMAT_BGRA5551_get();
  public final static int SDL_PIXELFORMAT_RGB565 = SDL2JNI.SDL_PIXELFORMAT_RGB565_get();
  public final static int SDL_PIXELFORMAT_BGR565 = SDL2JNI.SDL_PIXELFORMAT_BGR565_get();
  public final static int SDL_PIXELFORMAT_RGB24 = SDL2JNI.SDL_PIXELFORMAT_RGB24_get();
  public final static int SDL_PIXELFORMAT_BGR24 = SDL2JNI.SDL_PIXELFORMAT_BGR24_get();
  public final static int SDL_PIXELFORMAT_RGB888 = SDL2JNI.SDL_PIXELFORMAT_RGB888_get();
  public final static int SDL_PIXELFORMAT_RGBX8888 = SDL2JNI.SDL_PIXELFORMAT_RGBX8888_get();
  public final static int SDL_PIXELFORMAT_BGR888 = SDL2JNI.SDL_PIXELFORMAT_BGR888_get();
  public final static int SDL_PIXELFORMAT_BGRX8888 = SDL2JNI.SDL_PIXELFORMAT_BGRX8888_get();
  public final static int SDL_PIXELFORMAT_ARGB8888 = SDL2JNI.SDL_PIXELFORMAT_ARGB8888_get();
  public final static int SDL_PIXELFORMAT_RGBA8888 = SDL2JNI.SDL_PIXELFORMAT_RGBA8888_get();
  public final static int SDL_PIXELFORMAT_ABGR8888 = SDL2JNI.SDL_PIXELFORMAT_ABGR8888_get();
  public final static int SDL_PIXELFORMAT_BGRA8888 = SDL2JNI.SDL_PIXELFORMAT_BGRA8888_get();
  public final static int SDL_PIXELFORMAT_ARGB2101010 = SDL2JNI.SDL_PIXELFORMAT_ARGB2101010_get();
  public final static int SDL_PIXELFORMAT_RGBA32 = SDL2JNI.SDL_PIXELFORMAT_RGBA32_get();
  public final static int SDL_PIXELFORMAT_ARGB32 = SDL2JNI.SDL_PIXELFORMAT_ARGB32_get();
  public final static int SDL_PIXELFORMAT_BGRA32 = SDL2JNI.SDL_PIXELFORMAT_BGRA32_get();
  public final static int SDL_PIXELFORMAT_ABGR32 = SDL2JNI.SDL_PIXELFORMAT_ABGR32_get();
  public final static int SDL_PIXELFORMAT_YV12 = SDL2JNI.SDL_PIXELFORMAT_YV12_get();
  public final static int SDL_PIXELFORMAT_IYUV = SDL2JNI.SDL_PIXELFORMAT_IYUV_get();
  public final static int SDL_PIXELFORMAT_YUY2 = SDL2JNI.SDL_PIXELFORMAT_YUY2_get();
  public final static int SDL_PIXELFORMAT_UYVY = SDL2JNI.SDL_PIXELFORMAT_UYVY_get();
  public final static int SDL_PIXELFORMAT_YVYU = SDL2JNI.SDL_PIXELFORMAT_YVYU_get();
  public final static int SDL_PIXELFORMAT_NV12 = SDL2JNI.SDL_PIXELFORMAT_NV12_get();
  public final static int SDL_PIXELFORMAT_NV21 = SDL2JNI.SDL_PIXELFORMAT_NV21_get();

}
