/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_JoyHatEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_JoyHatEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_JoyHatEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_JoyHatEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_JoyHatEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_JoyHatEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_JoyHatEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_JoyHatEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(SWIGTYPE_p_SDL_JoystickID value) {
    SDL2JNI.SDL_JoyHatEvent_which_set(swigCPtr, this, SWIGTYPE_p_SDL_JoystickID.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_JoystickID getWhich() {
    return new SWIGTYPE_p_SDL_JoystickID(SDL2JNI.SDL_JoyHatEvent_which_get(swigCPtr, this), true);
  }

  public void setHat(short value) {
    SDL2JNI.SDL_JoyHatEvent_hat_set(swigCPtr, this, value);
  }

  public short getHat() {
    return SDL2JNI.SDL_JoyHatEvent_hat_get(swigCPtr, this);
  }

  public void setValue(short value) {
    SDL2JNI.SDL_JoyHatEvent_value_set(swigCPtr, this, value);
  }

  public short getValue() {
    return SDL2JNI.SDL_JoyHatEvent_value_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    SDL2JNI.SDL_JoyHatEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return SDL2JNI.SDL_JoyHatEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    SDL2JNI.SDL_JoyHatEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return SDL2JNI.SDL_JoyHatEvent_padding2_get(swigCPtr, this);
  }

  public SDL_JoyHatEvent() {
    this(SDL2JNI.new_SDL_JoyHatEvent(), true);
  }

}
