/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class SDL_GLContextResetNotification {
  public final static SDL_GLContextResetNotification SDL_GL_CONTEXT_RESET_NO_NOTIFICATION = new SDL_GLContextResetNotification("SDL_GL_CONTEXT_RESET_NO_NOTIFICATION", SDL2JNI.SDL_GL_CONTEXT_RESET_NO_NOTIFICATION_get());
  public final static SDL_GLContextResetNotification SDL_GL_CONTEXT_RESET_LOSE_CONTEXT = new SDL_GLContextResetNotification("SDL_GL_CONTEXT_RESET_LOSE_CONTEXT", SDL2JNI.SDL_GL_CONTEXT_RESET_LOSE_CONTEXT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_GLContextResetNotification swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_GLContextResetNotification.class + " with value " + swigValue);
  }

  private SDL_GLContextResetNotification(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_GLContextResetNotification(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_GLContextResetNotification(String swigName, SDL_GLContextResetNotification swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_GLContextResetNotification[] swigValues = { SDL_GL_CONTEXT_RESET_NO_NOTIFICATION, SDL_GL_CONTEXT_RESET_LOSE_CONTEXT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

