/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_ControllerAxisEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_ControllerAxisEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_ControllerAxisEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_ControllerAxisEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_ControllerAxisEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_ControllerAxisEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_ControllerAxisEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_ControllerAxisEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(SWIGTYPE_p_SDL_JoystickID value) {
    SDL2JNI.SDL_ControllerAxisEvent_which_set(swigCPtr, this, SWIGTYPE_p_SDL_JoystickID.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_JoystickID getWhich() {
    return new SWIGTYPE_p_SDL_JoystickID(SDL2JNI.SDL_ControllerAxisEvent_which_get(swigCPtr, this), true);
  }

  public void setAxis(short value) {
    SDL2JNI.SDL_ControllerAxisEvent_axis_set(swigCPtr, this, value);
  }

  public short getAxis() {
    return SDL2JNI.SDL_ControllerAxisEvent_axis_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    SDL2JNI.SDL_ControllerAxisEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return SDL2JNI.SDL_ControllerAxisEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    SDL2JNI.SDL_ControllerAxisEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return SDL2JNI.SDL_ControllerAxisEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    SDL2JNI.SDL_ControllerAxisEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return SDL2JNI.SDL_ControllerAxisEvent_padding3_get(swigCPtr, this);
  }

  public void setValue(SWIGTYPE_p_Sint16 value) {
    SDL2JNI.SDL_ControllerAxisEvent_value_set(swigCPtr, this, SWIGTYPE_p_Sint16.getCPtr(value));
  }

  public SWIGTYPE_p_Sint16 getValue() {
    return new SWIGTYPE_p_Sint16(SDL2JNI.SDL_ControllerAxisEvent_value_get(swigCPtr, this), true);
  }

  public void setPadding4(int value) {
    SDL2JNI.SDL_ControllerAxisEvent_padding4_set(swigCPtr, this, value);
  }

  public int getPadding4() {
    return SDL2JNI.SDL_ControllerAxisEvent_padding4_get(swigCPtr, this);
  }

  public SDL_ControllerAxisEvent() {
    this(SDL2JNI.new_SDL_ControllerAxisEvent(), true);
  }

}
