/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_DropEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_DropEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_DropEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_DropEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_DropEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_DropEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_DropEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_DropEvent_timestamp_get(swigCPtr, this);
  }

  public void setFile(String value) {
    SDL2JNI.SDL_DropEvent_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return SDL2JNI.SDL_DropEvent_file_get(swigCPtr, this);
  }

  public void setWindowID(long value) {
    SDL2JNI.SDL_DropEvent_windowID_set(swigCPtr, this, value);
  }

  public long getWindowID() {
    return SDL2JNI.SDL_DropEvent_windowID_get(swigCPtr, this);
  }

  public SDL_DropEvent() {
    this(SDL2JNI.new_SDL_DropEvent(), true);
  }

}
