/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_UserEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_UserEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_UserEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_UserEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_UserEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_UserEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_UserEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_UserEvent_timestamp_get(swigCPtr, this);
  }

  public void setWindowID(long value) {
    SDL2JNI.SDL_UserEvent_windowID_set(swigCPtr, this, value);
  }

  public long getWindowID() {
    return SDL2JNI.SDL_UserEvent_windowID_get(swigCPtr, this);
  }

  public void setCode(SWIGTYPE_p_Sint32 value) {
    SDL2JNI.SDL_UserEvent_code_set(swigCPtr, this, SWIGTYPE_p_Sint32.getCPtr(value));
  }

  public SWIGTYPE_p_Sint32 getCode() {
    return new SWIGTYPE_p_Sint32(SDL2JNI.SDL_UserEvent_code_get(swigCPtr, this), true);
  }

  public void setData1(SWIGTYPE_p_void value) {
    SDL2JNI.SDL_UserEvent_data1_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData1() {
    long cPtr = SDL2JNI.SDL_UserEvent_data1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setData2(SWIGTYPE_p_void value) {
    SDL2JNI.SDL_UserEvent_data2_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData2() {
    long cPtr = SDL2JNI.SDL_UserEvent_data2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SDL_UserEvent() {
    this(SDL2JNI.new_SDL_UserEvent(), true);
  }

}
