/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_KeyboardEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_KeyboardEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_KeyboardEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_KeyboardEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_KeyboardEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_KeyboardEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_KeyboardEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_KeyboardEvent_timestamp_get(swigCPtr, this);
  }

  public void setWindowID(long value) {
    SDL2JNI.SDL_KeyboardEvent_windowID_set(swigCPtr, this, value);
  }

  public long getWindowID() {
    return SDL2JNI.SDL_KeyboardEvent_windowID_get(swigCPtr, this);
  }

  public void setState(short value) {
    SDL2JNI.SDL_KeyboardEvent_state_set(swigCPtr, this, value);
  }

  public short getState() {
    return SDL2JNI.SDL_KeyboardEvent_state_get(swigCPtr, this);
  }

  public void setRepeat(short value) {
    SDL2JNI.SDL_KeyboardEvent_repeat_set(swigCPtr, this, value);
  }

  public short getRepeat() {
    return SDL2JNI.SDL_KeyboardEvent_repeat_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    SDL2JNI.SDL_KeyboardEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return SDL2JNI.SDL_KeyboardEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    SDL2JNI.SDL_KeyboardEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return SDL2JNI.SDL_KeyboardEvent_padding3_get(swigCPtr, this);
  }

  public void setKeysym(SWIGTYPE_p_SDL_Keysym value) {
    SDL2JNI.SDL_KeyboardEvent_keysym_set(swigCPtr, this, SWIGTYPE_p_SDL_Keysym.getCPtr(value));
  }

  public SWIGTYPE_p_SDL_Keysym getKeysym() {
    return new SWIGTYPE_p_SDL_Keysym(SDL2JNI.SDL_KeyboardEvent_keysym_get(swigCPtr, this), true);
  }

  public SDL_KeyboardEvent() {
    this(SDL2JNI.new_SDL_KeyboardEvent(), true);
  }

}
