/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class SDL_RendererFlip {
  public final static SDL_RendererFlip SDL_FLIP_NONE = new SDL_RendererFlip("SDL_FLIP_NONE", SDL2JNI.SDL_FLIP_NONE_get());
  public final static SDL_RendererFlip SDL_FLIP_HORIZONTAL = new SDL_RendererFlip("SDL_FLIP_HORIZONTAL", SDL2JNI.SDL_FLIP_HORIZONTAL_get());
  public final static SDL_RendererFlip SDL_FLIP_VERTICAL = new SDL_RendererFlip("SDL_FLIP_VERTICAL", SDL2JNI.SDL_FLIP_VERTICAL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_RendererFlip swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_RendererFlip.class + " with value " + swigValue);
  }

  private SDL_RendererFlip(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_RendererFlip(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_RendererFlip(String swigName, SDL_RendererFlip swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_RendererFlip[] swigValues = { SDL_FLIP_NONE, SDL_FLIP_HORIZONTAL, SDL_FLIP_VERTICAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

