/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_JoyDeviceEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_JoyDeviceEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_JoyDeviceEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_JoyDeviceEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_JoyDeviceEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_JoyDeviceEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_JoyDeviceEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_JoyDeviceEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(SWIGTYPE_p_Sint32 value) {
    SDL2JNI.SDL_JoyDeviceEvent_which_set(swigCPtr, this, SWIGTYPE_p_Sint32.getCPtr(value));
  }

  public SWIGTYPE_p_Sint32 getWhich() {
    return new SWIGTYPE_p_Sint32(SDL2JNI.SDL_JoyDeviceEvent_which_get(swigCPtr, this), true);
  }

  public SDL_JoyDeviceEvent() {
    this(SDL2JNI.new_SDL_JoyDeviceEvent(), true);
  }

}
