/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class SDL_GLcontextReleaseFlag {
  public final static SDL_GLcontextReleaseFlag SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE = new SDL_GLcontextReleaseFlag("SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE", SDL2JNI.SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE_get());
  public final static SDL_GLcontextReleaseFlag SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = new SDL_GLcontextReleaseFlag("SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH", SDL2JNI.SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_GLcontextReleaseFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_GLcontextReleaseFlag.class + " with value " + swigValue);
  }

  private SDL_GLcontextReleaseFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_GLcontextReleaseFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_GLcontextReleaseFlag(String swigName, SDL_GLcontextReleaseFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_GLcontextReleaseFlag[] swigValues = { SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

