/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_Color {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_Color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    SDL2JNI.SDL_Color_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return SDL2JNI.SDL_Color_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    SDL2JNI.SDL_Color_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return SDL2JNI.SDL_Color_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    SDL2JNI.SDL_Color_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return SDL2JNI.SDL_Color_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    SDL2JNI.SDL_Color_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return SDL2JNI.SDL_Color_a_get(swigCPtr, this);
  }

  public SDL_Color() {
    this(SDL2JNI.new_SDL_Color(), true);
  }

}
