/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_AudioDeviceEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_AudioDeviceEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_AudioDeviceEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_AudioDeviceEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_AudioDeviceEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_AudioDeviceEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_AudioDeviceEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_AudioDeviceEvent_timestamp_get(swigCPtr, this);
  }

  public void setWhich(long value) {
    SDL2JNI.SDL_AudioDeviceEvent_which_set(swigCPtr, this, value);
  }

  public long getWhich() {
    return SDL2JNI.SDL_AudioDeviceEvent_which_get(swigCPtr, this);
  }

  public void setIscapture(short value) {
    SDL2JNI.SDL_AudioDeviceEvent_iscapture_set(swigCPtr, this, value);
  }

  public short getIscapture() {
    return SDL2JNI.SDL_AudioDeviceEvent_iscapture_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    SDL2JNI.SDL_AudioDeviceEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return SDL2JNI.SDL_AudioDeviceEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    SDL2JNI.SDL_AudioDeviceEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return SDL2JNI.SDL_AudioDeviceEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    SDL2JNI.SDL_AudioDeviceEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return SDL2JNI.SDL_AudioDeviceEvent_padding3_get(swigCPtr, this);
  }

  public SDL_AudioDeviceEvent() {
    this(SDL2JNI.new_SDL_AudioDeviceEvent(), true);
  }

}
