/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class SDL_TextureModulate {
  public final static SDL_TextureModulate SDL_TEXTUREMODULATE_NONE = new SDL_TextureModulate("SDL_TEXTUREMODULATE_NONE", SDL2JNI.SDL_TEXTUREMODULATE_NONE_get());
  public final static SDL_TextureModulate SDL_TEXTUREMODULATE_COLOR = new SDL_TextureModulate("SDL_TEXTUREMODULATE_COLOR", SDL2JNI.SDL_TEXTUREMODULATE_COLOR_get());
  public final static SDL_TextureModulate SDL_TEXTUREMODULATE_ALPHA = new SDL_TextureModulate("SDL_TEXTUREMODULATE_ALPHA", SDL2JNI.SDL_TEXTUREMODULATE_ALPHA_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_TextureModulate swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_TextureModulate.class + " with value " + swigValue);
  }

  private SDL_TextureModulate(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_TextureModulate(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_TextureModulate(String swigName, SDL_TextureModulate swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_TextureModulate[] swigValues = { SDL_TEXTUREMODULATE_NONE, SDL_TEXTUREMODULATE_COLOR, SDL_TEXTUREMODULATE_ALPHA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

