/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public final class SDL_HitTestResult {
  public final static SDL_HitTestResult SDL_HITTEST_NORMAL = new SDL_HitTestResult("SDL_HITTEST_NORMAL");
  public final static SDL_HitTestResult SDL_HITTEST_DRAGGABLE = new SDL_HitTestResult("SDL_HITTEST_DRAGGABLE");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_TOPLEFT = new SDL_HitTestResult("SDL_HITTEST_RESIZE_TOPLEFT");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_TOP = new SDL_HitTestResult("SDL_HITTEST_RESIZE_TOP");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_TOPRIGHT = new SDL_HitTestResult("SDL_HITTEST_RESIZE_TOPRIGHT");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_RIGHT = new SDL_HitTestResult("SDL_HITTEST_RESIZE_RIGHT");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_BOTTOMRIGHT = new SDL_HitTestResult("SDL_HITTEST_RESIZE_BOTTOMRIGHT");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_BOTTOM = new SDL_HitTestResult("SDL_HITTEST_RESIZE_BOTTOM");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_BOTTOMLEFT = new SDL_HitTestResult("SDL_HITTEST_RESIZE_BOTTOMLEFT");
  public final static SDL_HitTestResult SDL_HITTEST_RESIZE_LEFT = new SDL_HitTestResult("SDL_HITTEST_RESIZE_LEFT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SDL_HitTestResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SDL_HitTestResult.class + " with value " + swigValue);
  }

  private SDL_HitTestResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SDL_HitTestResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SDL_HitTestResult(String swigName, SDL_HitTestResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SDL_HitTestResult[] swigValues = { SDL_HITTEST_NORMAL, SDL_HITTEST_DRAGGABLE, SDL_HITTEST_RESIZE_TOPLEFT, SDL_HITTEST_RESIZE_TOP, SDL_HITTEST_RESIZE_TOPRIGHT, SDL_HITTEST_RESIZE_RIGHT, SDL_HITTEST_RESIZE_BOTTOMRIGHT, SDL_HITTEST_RESIZE_BOTTOM, SDL_HITTEST_RESIZE_BOTTOMLEFT, SDL_HITTEST_RESIZE_LEFT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

