/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_DisplayMode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_DisplayMode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_DisplayMode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_DisplayMode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFormat(long value) {
    SDL2JNI.SDL_DisplayMode_format_set(swigCPtr, this, value);
  }

  public long getFormat() {
    return SDL2JNI.SDL_DisplayMode_format_get(swigCPtr, this);
  }

  public void setW(int value) {
    SDL2JNI.SDL_DisplayMode_w_set(swigCPtr, this, value);
  }

  public int getW() {
    return SDL2JNI.SDL_DisplayMode_w_get(swigCPtr, this);
  }

  public void setH(int value) {
    SDL2JNI.SDL_DisplayMode_h_set(swigCPtr, this, value);
  }

  public int getH() {
    return SDL2JNI.SDL_DisplayMode_h_get(swigCPtr, this);
  }

  public void setRefresh_rate(int value) {
    SDL2JNI.SDL_DisplayMode_refresh_rate_set(swigCPtr, this, value);
  }

  public int getRefresh_rate() {
    return SDL2JNI.SDL_DisplayMode_refresh_rate_get(swigCPtr, this);
  }

  public void setDriverdata(SWIGTYPE_p_void value) {
    SDL2JNI.SDL_DisplayMode_driverdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getDriverdata() {
    long cPtr = SDL2JNI.SDL_DisplayMode_driverdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SDL_DisplayMode() {
    this(SDL2JNI.new_SDL_DisplayMode(), true);
  }

}
