/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SDL_WindowEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SDL_WindowEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDL_WindowEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SDL2JNI.delete_SDL_WindowEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(long value) {
    SDL2JNI.SDL_WindowEvent_type_set(swigCPtr, this, value);
  }

  public long getType() {
    return SDL2JNI.SDL_WindowEvent_type_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    SDL2JNI.SDL_WindowEvent_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return SDL2JNI.SDL_WindowEvent_timestamp_get(swigCPtr, this);
  }

  public void setWindowID(long value) {
    SDL2JNI.SDL_WindowEvent_windowID_set(swigCPtr, this, value);
  }

  public long getWindowID() {
    return SDL2JNI.SDL_WindowEvent_windowID_get(swigCPtr, this);
  }

  public void setEvent(short value) {
    SDL2JNI.SDL_WindowEvent_event_set(swigCPtr, this, value);
  }

  public short getEvent() {
    return SDL2JNI.SDL_WindowEvent_event_get(swigCPtr, this);
  }

  public void setPadding1(short value) {
    SDL2JNI.SDL_WindowEvent_padding1_set(swigCPtr, this, value);
  }

  public short getPadding1() {
    return SDL2JNI.SDL_WindowEvent_padding1_get(swigCPtr, this);
  }

  public void setPadding2(short value) {
    SDL2JNI.SDL_WindowEvent_padding2_set(swigCPtr, this, value);
  }

  public short getPadding2() {
    return SDL2JNI.SDL_WindowEvent_padding2_get(swigCPtr, this);
  }

  public void setPadding3(short value) {
    SDL2JNI.SDL_WindowEvent_padding3_set(swigCPtr, this, value);
  }

  public short getPadding3() {
    return SDL2JNI.SDL_WindowEvent_padding3_get(swigCPtr, this);
  }

  public void setData1(int value) {
    SDL2JNI.SDL_WindowEvent_data1_set(swigCPtr, this, value);
  }

  public int getData1() {
    return SDL2JNI.SDL_WindowEvent_data1_get(swigCPtr, this);
  }

  public void setData2(int value) {
    SDL2JNI.SDL_WindowEvent_data2_set(swigCPtr, this, value);
  }

  public int getData2() {
    return SDL2JNI.SDL_WindowEvent_data2_get(swigCPtr, this);
  }

  public SDL_WindowEvent() {
    this(SDL2JNI.new_SDL_WindowEvent(), true);
  }

}
