/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SWIGTYPE_p_f_p_void_p_union_SDL_Event__int {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_p_union_SDL_Event__int(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_p_union_SDL_Event__int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_p_union_SDL_Event__int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

