/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SWIGTYPE_p_f_p_struct__GIOChannel_p_char_unsigned_long_long_p_unsigned_long_long_p_p_struct__GError__GIOStatus {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_struct__GIOChannel_p_char_unsigned_long_long_p_unsigned_long_long_p_p_struct__GError__GIOStatus(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct__GIOChannel_p_char_unsigned_long_long_p_unsigned_long_long_p_p_struct__GError__GIOStatus() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct__GIOChannel_p_char_unsigned_long_long_p_unsigned_long_long_p_p_struct__GError__GIOStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

