/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sdl2cairo;

public class SWIGTYPE_p_p_f_p_struct__cairo_pattern_p_void_p_struct__cairo_surface_p_q_const__struct__cairo_rectangle_int__p__cairo_surface {
  private transient long swigCPtr;

  protected SWIGTYPE_p_p_f_p_struct__cairo_pattern_p_void_p_struct__cairo_surface_p_q_const__struct__cairo_rectangle_int__p__cairo_surface(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_f_p_struct__cairo_pattern_p_void_p_struct__cairo_surface_p_q_const__struct__cairo_rectangle_int__p__cairo_surface() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_f_p_struct__cairo_pattern_p_void_p_struct__cairo_surface_p_q_const__struct__cairo_rectangle_int__p__cairo_surface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

